/* DailyFlow — conteúdo da revisão do planejamento.
 * Fonte: daily-os-product-functional-spec.md (v0.1) + lacunas identificadas.
 * src: 'spec' = está na spec · 'derivada' = implícita na spec, sem história/fluxo explícito · 'nova' = proposta nova
 */
const CONTENT = {

/* ───────────────────────── Um dia no DailyFlow ───────────────────────── */
day: [
  { id:'DIA-01', t:'05:55', dev:'Desktop', st:'nao', do:'Abro o DailyFlow.', app:'Mostra “Bom dia · Segunda, 28 set” com o dia já preparado: template Weekday, 2 reuniões do trabalho, 1 tarefa para continuar e 3 itens no Inbox. Dois caminhos: Planejar meu dia ou Modo rápido.', flow:'F-01' },
  { id:'DIA-02', t:'05:56', dev:'Desktop', st:'plan', do:'Leio o contexto (Etapa 1) e já marco o que entra hoje: 3 tarefas e o dentista às 16:00.', app:'Destaca “Fix Sortie sync · 1h42 rastreado · 4 sessões” em Continuar e a consulta da Ana (Awareness, não ocupa tempo). Cada item tem “Para hoje”; compromissos novos entram como bloco Fixo ali mesmo.', flow:'F-01' },
  { id:'DIA-03', t:'05:58', dev:'Desktop', st:'plan', do:'Monto o dia (Etapa 2): vejo o template com o dentista e, ao lado, as tarefas que marquei. Ajusto os blocos e solto as tarefas neles na mesma tela.', app:'Esqueleto e alocação juntos: dá para decidir se Music às 11:00 cabe sabendo o que precisa ser feito. O template original não muda.', flow:'F-01' },
  { id:'DIA-04', t:'06:00', dev:'Desktop', st:'plan', do:'Lembro de “ligar para a oficina” no meio do planejamento: aperto N, digito e ela aparece no painel. Ao arrastar uma tarefa Maker, os blocos Maker se destacam.', app:'Captura sem sair do planejamento. Blocos da mesma área ficam em destaque; soltar numa área diferente mostra um aviso leve. O Maker mostra 3h40 estimado / 3h disponível.', flow:'F-01' },
  { id:'DIA-05', t:'06:01', dev:'Desktop', st:'plan', do:'Vejo o aviso de capacidade e escolho Manter mesmo assim (Etapa 3). Clico INICIAR DIA.', app:'Salva o Baseline imutável. A tela muda de planejamento para execução: Agora · Próximo · Hoje.', flow:'F-01' },
  { id:'DIA-06', t:'06:02', dev:'Desktop', st:'ativo', do:'Clico ▶ em “Fix Sortie sync”, preset 50/10.', app:'Sessão de foco começa. O registro de tempo fica ligado à tarefa, ao bloco Maker e à área Maker.', flow:'F-15' },
  { id:'DIA-07', t:'08:55', dev:'Desktop', st:'ativo', do:'O bloco Maker termina. Paro a sessão.', app:'Agora passa a ser “Drive / Felipe”. A tarefa continua Em andamento (sessão ≠ tarefa).', flow:'F-15' },
  { id:'DIA-08', t:'09:20', dev:'Celular', st:'ativo', do:'Parado no carro, toco + e digito “Comprar PETG”.', app:'Vai direto para o Inbox. Nenhuma pergunta, nenhum campo obrigatório.', flow:'F-11' },
  { id:'DIA-09', t:'10:05', dev:'Desktop', st:'ativo', do:'Toco “Comecei” no bloco Work.', app:'Registro ao vivo inicia às 10:05 (o plano dizia 10:00; a diferença fica registrada, sem julgamento).', flow:'F-16' },
  { id:'DIA-10', t:'10:42', dev:'Desktop', st:'ativo', do:'Chega uma reunião nova 11:30–12:00 no Outlook. Escolho Mover Música para 13:00.', app:'Banner de conflito com 5 opções. Cria a Revisão #1 (motivo: conflito de calendário). O Baseline continua intacto.', flow:'F-03' },
  { id:'DIA-11', t:'12:00', dev:'—', st:'ativo', do:'Almoço. Não abro o app.', app:'Nada acontece. A lacuna 12:00–13:05 fica para ser resolvida no fechamento.', flow:'F-04' },
  { id:'DIA-12', t:'14:00', dev:'Desktop', st:'ativo', do:'O bloco “Focus Work” já estava publicado como Busy no Outlook.', app:'Colegas veem o horário ocupado. Se eu mover o bloco, o evento externo move junto.', flow:'F-07' },
  { id:'DIA-13', t:'17:30', dev:'Celular', st:'ativo', do:'Olho o celular (PWA ou, no futuro, widget).', app:'AGORA Drive / Felipe · até 18:30 · PRÓXIMO Família.', flow:'F-10' },
  { id:'DIA-14', t:'18:30', dev:'—', st:'ativo', do:'Família. Bloco aberto, sem tarefas, sem timer.', app:'Nada a fazer. Tempo aberto é tempo válido.', flow:'F-06' },
  { id:'DIA-15', t:'21:00', dev:'Desktop', st:'fech', do:'Clico Fechar dia. Passo 1: preencho a lacuna 12:00–13:05 como Almoço e confirmo Família.', app:'Mostra a linha do tempo real com lacunas e sobreposições destacadas e ações de 1 clique.', flow:'F-01' },
  { id:'DIA-16', t:'21:03', dev:'Desktop', st:'fech', do:'Passo 2: reviso tarefas. Passo 3: pulo a reflexão.', app:'2 concluídas. “Fix Sortie sync” volta ao Backlog com todo o histórico. Reflexão nunca bloqueia.', flow:'F-01' },
  { id:'DIA-17', t:'21:05', dev:'Desktop', st:'fechado', do:'Vejo o resumo e fecho o app.', app:'Planejado 15h00 · Registrado 14h12 · distribuição por área. Dia FECHADO (pode ser reaberto). Tudo já sincronizado.', flow:'F-01' },
  { id:'DIA-18', t:'Amanhã', dev:'Desktop', st:'nao', do:'Abro o app de novo.', app:'“Fix Sortie sync” aparece em Continuar de dias anteriores. Eu decido se entra hoje; nada rola sozinho.', flow:'F-05' },
],

/* ───────────────────────── Fluxos ponta a ponta ───────────────────────── */
flows: [
  { id:'F-00', title:'Primeiro acesso e configuração inicial', src:'nova', when:'config', phase:'MVP',
    trigger:'Abro o DailyFlow pela primeira vez num navegador.',
    goal:'Sair do zero para um primeiro dia planejado em menos de 3 minutos, com tudo pulável.',
    steps:[
      ['Acesso','Digito meu código privado.','Valida no servidor (hash, nunca texto puro), cria sessão longa e registra o dispositivo.'],
      ['Boas-vindas','Vejo 3 passos opcionais: Áreas, Templates, Calendários.','Cada passo tem Pular. Os padrões da spec já vêm preenchidos.'],
      ['Áreas de vida','Reviso as 11 áreas (nome, cor, ícone). Removo ou renomeio.','Salva. Cores seguem os acentos do design system.'],
      ['Templates','Vejo Weekday e Weekend pré-carregados. Ajusto horários arrastando.','Salva o template. Nada é aplicado a dias já iniciados.'],
      ['Calendários (Fase 2)','Conecto Google e/ou Microsoft, ou clico Depois.','OAuth, lista de calendários e classificação padrão por calendário (Commitment / Awareness / ocultar).'],
      ['Instalar','Recebo a sugestão de instalar como app (PWA).','Opcional. Nunca aparece de novo se eu recusar.'],
      ['Hoje','Caio no estado Não planejado.','Mostra o dia preparado e os botões Planejar meu dia / Modo rápido.'],
    ],
    branches:[['Código errado','Mensagem clara, sem bloquear por tempo nas primeiras tentativas.'],['Pulo tudo','Uso os padrões da spec e configuro depois em Configurações.']],
    outcome:'App pronto, dispositivo confiável, primeiro dia aberto.',
    stories:['US-ACCESS-001','US-ACCESS-002','US-SET-001','US-SET-002','US-CAL-001'], questions:['Q-02','Q-27'] },

  { id:'F-01', title:'Dia útil completo, do abrir ao fechar', src:'spec', ref:'Jornada A · §95', when:'dia', phase:'MVP',
    trigger:'Segunda-feira, 05:55. Abro o app no desktop.',
    goal:'Planejar com intenção, executar seguindo Agora/Próximo, adaptar sem culpa e fechar o dia com o real registrado.',
    steps:[
      ['Hoje · Não planejado','Abro o app.','Já preparou: template Weekday, eventos Google + Microsoft, tarefas em andamento, prazos, Inbox.'],
      ['Etapa 1 · Contexto','Leio compromissos, awareness, em andamento, prazos e Inbox. Marco o que entra hoje e adiciono compromissos que faltam.','“Para hoje” em cada tarefa; “+ Compromisso” cria um bloco Fixo. [Continuar].'],
      ['Etapa 2 · Montar o dia','Ajusto blocos (mover, redimensionar, Fixo/Flexível) e arrasto as tarefas marcadas para dentro deles, na mesma tela.','Blocos do template tracejados até serem aceitos. Blocos da área da tarefa se destacam ao arrastar. Capacidade atualiza na hora.'],
      ['Etapa 2 · Montar o dia','Lembro de algo no meio: N, digito, Enter.','A tarefa aparece no painel pronta para arrastar. Compromisso novo: clique num horário vazio.'],
      ['Etapa 3 · Conflitos','Resolvo o que o sistema apontou: blocos lotados, sobreposições, tarefa em bloco de outra área.','Para cada item: Manter mesmo assim / Mover tarefa / Redimensionar bloco / Voltar ao Backlog.'],
      ['Etapa 4 · Iniciar','Clico INICIAR DIA.','Salva o Baseline imutável. A interface muda para execução: Agora · Próximo · Hoje.'],
      ['Hoje · Ativo','Inicio uma sessão de foco numa tarefa.','Timer no painel Agora. Registro de tempo ligado a tarefa + bloco + área.'],
      ['Hoje · Ativo','Blocos vão passando.','A linha NOW cruza a timeline. Blocos passados ganham ✓ quando têm registro real.'],
      ['Conflito','Chega uma reunião que colide com Música.','Banner: Manter sobreposição / Mover / Encurtar / Remover / Replanejar restante. Gera Revisão.'],
      ['Hoje · Ativo','Concluo uma tarefa.','Status Completed, horário de conclusão, tempo total acumulado.'],
      ['Fechar · Passo 1','Clico Fechar dia e reparo a linha do tempo real.','Destaca lacunas e sobreposições. Ações: Preencher, Estender anterior, Começar o próximo antes, Tempo aberto, Ignorar.'],
      ['Fechar · Passo 2','Reviso as tarefas.','Grupos Concluídas / Em andamento / Não iniciadas. As não concluídas voltam ao Backlog com histórico.'],
      ['Fechar · Passo 3','Reflexão opcional: nota, energia, algo incomum.','Nunca bloqueia. Pular é um clique.'],
      ['Fechar · Passo 4','Vejo o resumo.','Planejado × Registrado e distribuição por área. Dia FECHADO, reabrível.'],
      ['—','Fecho o app.','Nada pendente. Tudo já está salvo localmente e sincronizado.'],
    ],
    branches:[['Não quero fazer o planejamento completo','Ver F-02 Manhã rápida.'],['Não rastreei nada durante o dia','Ver F-04.'],['Não fechei o dia','Ver F-13 no dia seguinte.']],
    outcome:'Baseline, Plano final e Real preservados. Tarefas inacabadas no Backlog, prontas para amanhã.',
    stories:['US-PLAN-001','US-PLAN-003','US-PLAN-004','US-PLAN-005','US-PLAN-006','US-PLAN-007','US-PLAN-008','US-EXEC-001','US-REVIEW-002','US-REVIEW-003','US-REVIEW-004'], questions:['Q-03','Q-05','Q-10','Q-11'] },

  { id:'F-02', title:'Manhã rápida (1 minuto)', src:'spec', ref:'Jornada B · §96 · §39', when:'manha', phase:'MVP',
    trigger:'Estou com pressa, mas quero que o dia tenha um plano.',
    goal:'Planejamento útil em 1 minuto. O assistente completo nunca é obrigatório.',
    steps:[
      ['Hoje · Não planejado','Clico Modo rápido.','Tela única: esqueleto do template + compromissos já montados + 3 tarefas sugeridas (em andamento e High).'],
      ['Modo rápido','Arrasto 1 tarefa High para um bloco (ou toco “colocar no próximo bloco compatível”).','Tarefa vira Planned.'],
      ['Modo rápido','Clico INICIAR DIA.','Baseline salvo. Modo execução.'],
    ],
    branches:[['Existe sobreposição de compromisso fixo','Aviso inline, não bloqueia o início.'],['Não quero nem isso','Ver Q-05: iniciar sem planejar (Baseline implícito).']],
    outcome:'Dia iniciado com Baseline em ~3 interações.',
    stories:['US-PLAN-010','US-PLAN-008'], questions:['Q-05'] },

  { id:'F-03', title:'Dia caótico com várias mudanças de plano', src:'spec', ref:'Jornada C · §97 · §44–47', when:'dia', phase:'MVP',
    trigger:'O dia começou normal e foi se desfazendo.',
    goal:'Adaptar sem culpa e, no fim, entender o que mudou e por quê.',
    steps:[
      ['Hoje · Ativo','09:10: aparece uma reunião 09:30–10:30 sobre o bloco Work.','Conflito. Escolho Encurtar Work. Revisão #1.'],
      ['Hoje · Ativo','11:00: a escola liga, preciso buscar o Felipe às 12:00. Adiciono um bloco Deslocamento 11:45–12:30 (Fixo).','Conflito com Música. Escolho Remover Música hoje. Revisão #2.'],
      ['Hoje · Ativo','13:00: o almoço atrasou; FlightSim não cabe mais. Clico Replanejar restante do dia.','Proposta determinística: FlightSim 30 min às 13:30, Work 14:00–18:00. Eu confirmo ou ajusto. Revisão #3.'],
      ['Inspector','Abro o histórico do dia.','Baseline → R1 → R2 → R3, com horário e motivo de cada mudança. A tela principal continua limpa.'],
      ['Fechar · Passo 1','Reconstruo o real.','Ponto de partida: plano final. Ajusto bordas arrastando.'],
      ['Histórico · dia','Comparo Baseline × Final × Real.','Mostra 3 revisões, 2 blocos removidos e 1h40 de variação, em linguagem neutra.'],
    ],
    branches:[['Não quero resolver o conflito agora','Manter sobreposição. O conflito fica sinalizado na timeline.']],
    outcome:'Nada é tratado como falha. As três camadas explicam o dia.',
    stories:['US-REPLAN-001','US-REPLAN-002','US-REPLAN-003','US-REPLAN-004','US-REPLAN-005','US-CAL-006'], questions:['Q-19','Q-25'] },

  { id:'F-04', title:'Esqueci de rastrear o dia inteiro', src:'spec', ref:'Jornada D · §98', when:'noite', phase:'MVP',
    trigger:'Planejei de manhã e não toquei no app até a noite.',
    goal:'Reconstruir o real em poucos minutos. Isso é um caso de sucesso normal.',
    steps:[
      ['Hoje · Ativo (noite)','Abro o app às 21:30.','Mostra “Nenhum registro real hoje” e o atalho Reconstruir a partir do plano.'],
      ['Fechar · Passo 1','Clico Aceitar plano final como real.','Cada bloco vira um registro (HISTORICAL_MANUAL) com a área do bloco.'],
      ['Fechar · Passo 1','Ajusto 3 bordas arrastando e adiciono DCS 20:00–21:00.','Recalcula lacunas e sobreposições.'],
      ['Fechar · Passo 1','Associo 2 tarefas a registros.','O tempo passa a contar nessas tarefas.'],
      ['Fechar · Passo 2','Marco 1 tarefa como concluída.','Completed com horário informado por mim.'],
      ['Fechar · Passo 4','Fecho o dia.','Resumo normal.'],
    ],
    branches:[['O dia não teve nada a ver com o plano','Começar do zero: timeline vazia com as áreas mais usadas como atalhos.']],
    outcome:'Dia completo sem ter usado timer.',
    stories:['US-TIME-004','US-TIME-008','US-REVIEW-002'], questions:['Q-03'] },

  { id:'F-05', title:'Tarefa demora muito mais que o estimado', src:'spec', ref:'Jornada E · §99 · §57', when:'dia', phase:'MVP',
    trigger:'“Implementar sync de calendário” estimada em 1h, alocada no Maker.',
    goal:'Deixar a tarefa aberta por quantas sessões forem precisas e aprender com a estimativa.',
    steps:[
      ['Hoje · Ativo','Faço 4 sessões 25/5.','Depois da 3ª, o card mostra 1h15 / 1h, de forma neutra.'],
      ['Timer','Finalizo a sessão.','Finalizar sessão não conclui a tarefa. Ela continua Em andamento.'],
      ['Fechar · Passo 2','A tarefa não foi concluída.','Volta ao Backlog: “1h40 rastreado · 4 sessões”.'],
      ['Amanhã · Contexto','Abro o planejamento.','Aparece em Continuar de dias anteriores. Eu decido se entra hoje.'],
      ['Insights · Estimativa','Semanas depois.','Categoria Desenvolvimento: média estimada 52m, real 78m, multiplicador 1,5×.'],
    ],
    branches:[['Quero reestimar','Ver Q-16: sugerir nova estimativa com base no histórico.']],
    outcome:'Histórico da tarefa intacto e calibração das estimativas.',
    stories:['US-TIME-002','US-TIME-006','US-TASK-004','US-TASK-005','US-TASK-006','US-STATS-003'], questions:['Q-16'] },

  { id:'F-06', title:'Tempo aberto com a família', src:'spec', ref:'Jornada F · §100 · §9', when:'dia', phase:'MVP',
    trigger:'Planejei 15:00–18:00 Família, sem tarefas.',
    goal:'Registrar tempo valioso sem burocracia.',
    steps:[
      ['Planejamento','Crio um bloco Aberto “Família” 15:00–18:00.','Não pede destino, tarefa nem timer.'],
      ['Hoje · Ativo','Opcional: toco Comecei às 15:10.','Registro ao vivo começa.'],
      ['Fechar · Passo 1','Ajusto o real para 15:10–18:20.','Pronto.'],
    ],
    branches:[['Não toquei em nada','No fechamento, Aceitar plano como real e ajustar se quiser.']],
    outcome:'Dado válido e completo.',
    stories:['US-EXEC-002'], questions:[] },

  { id:'F-07', title:'Proteger tempo de foco na agenda do trabalho', src:'spec', ref:'Jornada G · §101 · §30–31', when:'qualquer', phase:'Fase 2',
    trigger:'Quero que colegas não marquem reunião no meu bloco de foco.',
    goal:'Publicar blocos como Busy e mantê-los sincronizados.',
    steps:[
      ['Timeline','Crio “Focus Work” 14:00–15:30.','Bloco interno.'],
      ['Inspector','Publicar → Microsoft · Disponibilidade Busy.','Cria o evento no Outlook marcado como pertencente ao DailyFlow. O bloco ganha um ícone de escudo.'],
      ['Timeline','Movo o bloco para 15:00.','O evento externo move junto.'],
      ['Timeline','Excluo o bloco.','Pergunta: Excluir só no DailyFlow / Excluir aqui e no calendário externo / Cancelar.'],
    ],
    branches:[['Falha ao publicar','Bloco mostra “Não publicado · Tentar de novo”.'],['Alguém marca reunião mesmo assim','Vira conflito normal (F-03).']],
    outcome:'Tempo protegido, e o DailyFlow só mexe nos eventos que ele mesmo criou.',
    stories:['US-CAL-004','US-CAL-005'], questions:['Q-20'] },

  { id:'F-08', title:'Corrigir um dia passado', src:'spec', ref:'Jornada H · §102 · §24', when:'qualquer', phase:'MVP',
    trigger:'Na quinta, lembro que a terça ficou incompleta.',
    goal:'Editar o real de qualquer dia sem tocar no Baseline.',
    steps:[
      ['Histórico','Abro o calendário e clico em terça.','Detalhe do dia com abas Baseline / Final / Real / Tarefas / Stats / Revisões.'],
      ['Detalhe · Real','Vejo uma lacuna de 1h e adiciono FlightSim 20:00–21:00.','Registro novo, marcado como edição histórica.'],
      ['Detalhe · Real','Mudo um registro de tarefa de 45m para 1h10.','O tempo da tarefa é recalculado.'],
      ['Detalhe','Salvo.','Estatísticas atualizam. O Baseline não muda.'],
    ],
    branches:[['O dia estava fechado','Editar reabre o dia automaticamente, ou peço para reabrir antes (ver Q-22).']],
    outcome:'Histórico corrigido e confiável.',
    stories:['US-TIME-005','US-REVIEW-005'], questions:['Q-22'] },

  { id:'F-09', title:'Dia offline', src:'spec', ref:'Jornada I · §103 · §74–75', when:'qualquer', phase:'MVP',
    trigger:'Perco a conexão com o Hoje aberto.',
    goal:'Nunca esperar a rede para usar o app.',
    steps:[
      ['Hoje','Abro o Hoje em cache.','Indicador discreto: Offline · alterações salvas neste dispositivo.'],
      ['Hoje','Adiciono tarefa, movo bloco, rodo sessão de foco, concluo tarefa, edito o real.','Tudo aplica na hora (banco local) e entra na fila.'],
      ['—','A conexão volta.','A fila sobe. O indicador vira Sincronizado.'],
    ],
    branches:[['Editei a mesma coisa em outro dispositivo','Mescla o que não conflita. Conflito real: aviso leve com escolha.']],
    outcome:'Nenhuma perda de dados, nenhuma espera.',
    stories:['US-OFFLINE-001','US-OFFLINE-002','US-OFFLINE-003','US-OFFLINE-004','US-OFFLINE-005'], questions:['Q-30'] },

  { id:'F-10', title:'Consultar pelo widget sem abrir o app', src:'spec', ref:'Jornada J · §104 · §81', when:'futuro', phase:'Fase 5',
    trigger:'Pego o celular.',
    goal:'Consciência do momento sem exigir interação.',
    steps:[
      ['Widget','Olho a tela inicial.','AGORA Work · 18 min restantes · PRÓXIMO Música 11:00.'],
      ['Widget','Toco no widget.','Abre o Hoje no app.'],
    ],
    branches:[], outcome:'Informação sem fricção.',
    stories:['US-WIDGET-001','US-WIDGET-003'], questions:[] },

  { id:'F-11', title:'Captura rápida de qualquer lugar', src:'derivada', ref:'§15 · §68 · §69', when:'qualquer', phase:'MVP',
    trigger:'Lembro de algo no meio de outra atividade.',
    goal:'Tirar da cabeça em menos de 5 segundos.',
    steps:[
      ['Qualquer tela','⌘K → Nova tarefa no Inbox (ou tecla N).','Campo único, foco imediato.'],
      ['Captura','Digito “Comprar PETG” e aperto Enter.','Vai para o Inbox. Toast “Adicionada ao Inbox · Desfazer”. Volto para onde estava.'],
      ['Celular','Toco + → Tarefa rápida.','Mesmo comportamento.'],
    ],
    branches:[['Estou no planejamento','A tarefa aparece direto no painel de tarefas, pronta para arrastar.']],
    outcome:'Inbox cresce sem exigir organização.',
    stories:['US-TASK-001','US-EXEC-005'], questions:['Q-15'] },

  { id:'F-12', title:'Triagem do Inbox', src:'nova', when:'qualquer', phase:'MVP',
    trigger:'O Inbox acumulou 7 itens.',
    goal:'Organizar rápido, com teclado.',
    steps:[
      ['Tarefas · Inbox','Abro o Inbox.','Lista com o primeiro item selecionado.'],
      ['Tarefas · Inbox','Para cada item: área (A), prioridade (1/2/3), estimativa (E).','Campos aparecem inline, sem abrir formulário.'],
      ['Tarefas · Inbox','Enviar ao Backlog, agendar para hoje, arquivar ou excluir.','Item sai do Inbox. Próximo item selecionado.'],
    ],
    branches:[['Faço a triagem durante o planejamento','Na Etapa 1, o Inbox aparece como contexto (ver Q-15).']],
    outcome:'Inbox zerado, Backlog organizado.',
    stories:['US-TASK-002','US-TASK-007'], questions:['Q-14','Q-15'] },

  { id:'F-13', title:'Abri o app e ontem não foi fechado', src:'nova', when:'manha', phase:'MVP',
    trigger:'Esqueci de fechar o dia anterior.',
    goal:'Resolver em segundos sem pular o dia de hoje.',
    steps:[
      ['Hoje · Não planejado','Abro o app.','Cartão: “Domingo não foi fechado.” Botões: Fechar agora · Fechar automaticamente · Depois.'],
      ['Fechar agora','Faço o fechamento resumido (Passos 1 e 2).','Mesmo fluxo da noite, sem reflexão.'],
      ['Fechar automaticamente','Escolho essa opção.','Tarefas não concluídas vão para o Backlog; o real fica como está; o dia fica marcado como “fechado automaticamente”.'],
      ['Hoje','Sigo para o planejamento de hoje.','Tarefas de ontem aparecem em Continuar de dias anteriores.'],
    ],
    branches:[['Deixei 3 dias sem fechar','Um cartão só, com “Fechar todos automaticamente”.']],
    outcome:'Nenhum dia fica “pendurado”.',
    stories:['US-REVIEW-006'], questions:['Q-06'] },

  { id:'F-14', title:'Abri o app tarde, com o dia já em andamento', src:'nova', when:'dia', phase:'MVP',
    trigger:'10:40, e o dia ainda não foi iniciado.',
    goal:'Planejar daqui para frente sem ter que justificar as horas que já passaram.',
    steps:[
      ['Hoje · Não planejado','Abro o app.','Template com os blocos anteriores a agora esmaecidos.'],
      ['Hoje','Clico Iniciar a partir de agora.','O Baseline considera só o período futuro e é marcado como “início tardio”.'],
      ['Hoje','Nos blocos passados, respondo “Isso aconteceu?” (Sim / Não / Ajustar) ou deixo para depois.','Sim vira registro real. Sem resposta, fica para o fechamento.'],
    ],
    branches:[],
    outcome:'O dia ainda tem plano e o passado não vira dívida.',
    stories:['US-PLAN-011'], questions:['Q-07'] },

  { id:'F-15', title:'Sessão de foco do início ao fim', src:'derivada', ref:'§20–22', when:'dia', phase:'MVP',
    trigger:'Quero trabalhar focado numa tarefa.',
    goal:'Rastrear foco sem atrito e corrigir erros com facilidade.',
    steps:[
      ['Tarefa / ⌘K','▶ Iniciar foco. Escolho o preset (o último usado vem selecionado).','Sessão começa. Tempo visível no painel Agora e no título da aba.'],
      ['Timer','Pauso e retomo.','Pausas não contam como foco.'],
      ['Timer','Fui interrompido: Parar.','Sessão fica registrada como interrompida, com a duração real.'],
      ['Timer','O foco de 25:00 termina.','Som suave. Opções: Iniciar pausa · +5 min · Finalizar sessão · Concluir tarefa.'],
      ['Timer','A pausa de 5:00 termina.','Próxima sessão ou Parar.'],
      ['Timer esquecido','Volto depois de 3h com o timer ligado.','“O timer está rodando há 3h12. Parou quando?” Escolho o horário e o registro é corrigido.'],
      ['Detalhe da tarefa','Edito ou excluo uma sessão acidental.','Tempo da tarefa recalculado.'],
    ],
    branches:[['A sessão atravessa o fim do bloco','Ver Q-10.'],['Inicio outra atividade com o timer rodando','Ver Q-11.']],
    outcome:'Sessões corretas, tarefa aberta até eu decidir concluir.',
    stories:['US-TIME-001','US-TIME-002','US-TIME-003','US-TIME-007'], questions:['Q-10','Q-11','Q-18'] },

  { id:'F-16', title:'Atividade fora do plano (troca rápida)', src:'nova', when:'dia', phase:'MVP',
    trigger:'Estou no bloco Work, mas vou tocar violão 20 minutos.',
    goal:'Registrar a realidade sem precisar replanejar.',
    steps:[
      ['⌘K / Agora','Iniciar atividade → Música (ou toco no chip da área).','Registro ao vivo de Música começa; a atividade anterior é encerrada.'],
      ['Agora','Paro depois de 20 min.','O real registra 20 min de Música. O plano não muda.'],
      ['Agora','Opcional: Refletir no plano.','Cria uma revisão, se eu quiser que o plano acompanhe.'],
    ],
    branches:[], outcome:'Real fiel, plano intacto.',
    stories:['US-EXEC-003'], questions:['Q-11'] },

  { id:'F-17', title:'Evento externo cancelado ou movido depois de iniciar o dia', src:'nova', when:'dia', phase:'Fase 2',
    trigger:'A reunião das 15:00 foi cancelada no Outlook.',
    goal:'Manter o plano atual fiel à agenda sem intervenção manual.',
    steps:[
      ['Sync','O sync detecta o cancelamento.','O bloco sai do plano atual e cria uma revisão automática (“evento cancelado”).'],
      ['Hoje · Ativo','Vejo o espaço livre.','Sugestão discreta: “1h liberada às 15:00. Mover algo para cá?”'],
    ],
    branches:[['O evento foi movido','Se colidir com algo, vira conflito normal (F-03).']],
    outcome:'O plano acompanha a realidade da agenda.',
    stories:['US-CAL-007'], questions:[] },

  { id:'F-18', title:'Editar um template', src:'nova', when:'config', phase:'MVP',
    trigger:'Minha rotina mudou: Música passa para 07:00.',
    goal:'Mudar o padrão sem afetar dias já iniciados.',
    steps:[
      ['Configurações · Templates','Abro o Weekday.','Timeline editável igual à do Hoje.'],
      ['Template','Arrasto e redimensiono blocos. Defino Fixo/Flexível e a área de cada um.','Salvo automaticamente.'],
      ['—','Pronto.','Vale a partir do próximo dia não iniciado. Hoje, se já iniciado, não muda.'],
    ],
    branches:[['Estou no Hoje e gostei do dia','Salvar hoje como template (ver Q-23).']],
    outcome:'Template atualizado, histórico preservado.',
    stories:['US-SET-001','US-PLAN-002'], questions:['Q-23'] },

  { id:'F-19', title:'Conectar e classificar calendários', src:'derivada', ref:'§26–29', when:'config', phase:'Fase 2',
    trigger:'Quero ver meus compromissos ao planejar.',
    goal:'Eventos certos bloqueando o tempo certo.',
    steps:[
      ['Configurações · Calendários','Conectar Google.','OAuth. Lista: Pessoal, Família (compartilhado), Feriados.'],
      ['Calendários','Defino o padrão de cada um: Pessoal → Commitment, Família → Awareness, Feriados → ocultar.','Salvo. Sync inicial.'],
      ['Calendários','Conectar Microsoft → Trabalho → Commitment.','Sync inicial.'],
      ['Hoje · Planejamento','Um evento da família precisa de mim.','No inspector do evento: mudar para Commitment só esse evento.'],
      ['Configurações · Sync','Vejo o status.','Última sincronização, erros e botão Tentar de novo.'],
    ],
    branches:[['O token expira','Aviso discreto no indicador de sync, com Reconectar.']],
    outcome:'Agenda externa integrada ao Hoje.',
    stories:['US-CAL-001','US-CAL-002','US-CAL-003','US-CAL-008','US-CAL-009'], questions:[] },

  { id:'F-20', title:'Fim de semana', src:'nova', when:'dia', phase:'MVP',
    trigger:'Sábado de manhã.',
    goal:'Leveza. Pouca estrutura, muito tempo aberto.',
    steps:[
      ['Hoje · Não planejado','Abro o app.','O template Weekend carrega automaticamente.'],
      ['Hoje','Aceito ou nem inicio o dia.','Blocos grandes e abertos: Família, Descanso, Lazer.'],
      ['Noite','Fecho o dia (opcional).','Resumo simples.'],
    ],
    branches:[['Não inicio o dia','Ver Q-05: Baseline implícito ou dia sem Baseline.']],
    outcome:'O app não cobra produtividade no fim de semana.',
    stories:['US-PLAN-001','US-PLAN-009'], questions:['Q-05','Q-06'] },

  { id:'F-21', title:'Revisão semanal', src:'nova', when:'noite', phase:'Fase 3',
    trigger:'Domingo à noite quero entender a semana.',
    goal:'Ajustar o modelo de tempo com base no que realmente aconteceu.',
    steps:[
      ['Insights · Semana','Abro a visão semanal.','Distribuição por área × semana passada, planejado × real, formato do dia.'],
      ['Insights','Vejo que Música ficou em 40 min na semana.','Dado descritivo, sem nota nem pontuação.'],
      ['Configurações','Ajusto o template ou a meta semanal da área.','Vale para a próxima semana.'],
    ],
    branches:[], outcome:'Ciclo de aprendizado fechado.',
    stories:['US-STATS-001','US-STATS-004','US-STATS-007','US-STATS-008'], questions:['Q-21'] },

  { id:'F-22', title:'Reabrir um dia fechado', src:'derivada', ref:'§52 · US-REVIEW-005', when:'qualquer', phase:'MVP',
    trigger:'Fechei o dia às 20h e depois joguei DCS até 22h.',
    goal:'Corrigir sem burocracia.',
    steps:[
      ['Hoje · Fechado','Clico Reabrir.','Volta para o estado Ativo (ou direto para o Passo 1 do fechamento).'],
      ['Real','Adiciono o registro.','Resumo recalculado.'],
      ['—','Fecho de novo.','Mantém o histórico de fechamentos.'],
    ],
    branches:[], outcome:'Dia correto.',
    stories:['US-REVIEW-005'], questions:['Q-22'] },

  { id:'F-23', title:'Dia que cruza a meia-noite', src:'nova', when:'noite', phase:'MVP',
    trigger:'Filme até 00:40, sono até 06:30.',
    goal:'Registrar sem cortar atividades artificialmente.',
    steps:[
      ['Hoje · Ativo','Continuo com um registro depois da meia-noite.','O registro pertence ao dia lógico em que começou (virada do dia configurável, ex.: 04:00).'],
      ['Amanhã','Abro o app às 06:30.','O dia novo começa limpo. O sono aparece como fim do dia anterior ou início do novo (ver Q-04).'],
    ],
    branches:[], outcome:'Sem registros quebrados à meia-noite.',
    stories:['US-SYS-001'], questions:['Q-04'] },
],

/* ───────────────────────── Histórias de usuário ───────────────────────── */
epics: [
  ['access','Acesso e instalação'],['plan','Planejamento do dia'],['exec','Execução (dia ativo)'],['task','Tarefas'],
  ['time','Registro de tempo e foco'],['replan','Replanejamento'],['review','Fechamento e revisão'],['cal','Calendários'],
  ['stats','Insights'],['set','Configurações e dados'],['offline','Offline e sincronização'],['sys','Regras de sistema'],['widget','Widgets e relógio (futuro)'],
],
stories: [
  ['US-ACCESS-001','access','nova','Quero entrar com um código privado uma vez por dispositivo e não precisar fazer login de novo.'],
  ['US-ACCESS-002','access','derivada','Quero instalar o DailyFlow como app (PWA) no desktop e no celular.'],

  ['US-PLAN-001','plan','spec','Quero que o template certo (Weekday ou Weekend) carregue automaticamente, para não reconstruir minha rotina todo dia.'],
  ['US-PLAN-002','plan','spec','Quero modificar o template de hoje sem alterar o template original.'],
  ['US-PLAN-003','plan','spec','Quero revisar meus compromissos externos antes de agendar atividades discricionárias.'],
  ['US-PLAN-004','plan','spec','Quero ver eventos Awareness sem que eles bloqueiem minha agenda.'],
  ['US-PLAN-005','plan','spec','Quero ver tarefas inacabadas de dias anteriores durante o planejamento.'],
  ['US-PLAN-006','plan','spec','Quero arrastar tarefas para blocos, conectando o que preciso fazer com quando pretendo fazer.'],
  ['US-PLAN-007','plan','spec','Quero ver quando as estimativas das tarefas passam da duração do bloco.'],
  ['US-PLAN-008','plan','spec','Quero iniciar meu dia com um Baseline Plan deliberado.'],
  ['US-PLAN-009','plan','nova','Quero trocar o template de hoje manualmente (ex.: feriado numa segunda usa o Weekend).'],
  ['US-PLAN-010','plan','derivada','Quero um modo rápido: aceitar o esqueleto, colocar uma tarefa e iniciar o dia em menos de 1 minuto.'],
  ['US-PLAN-011','plan','nova','Quero planejar mesmo abrindo o app tarde, sem ter que justificar as horas que já passaram.'],
  ['US-PLAN-012','plan','nova','Quero, opcionalmente, planejar o dia seguinte na noite anterior.'],
  ['US-PLAN-013','plan','derivada','Quero ver prazos próximos durante o planejamento.'],
  ['US-PLAN-014','plan','derivada','Quero criar um bloco arrastando uma tarefa para um horário vazio, com duração sugerida pela estimativa.'],

  ['US-EXEC-001','exec','derivada','Quero ver em segundos o que estou fazendo agora, quanto falta e o que vem depois.'],
  ['US-EXEC-002','exec','nova','Quero marcar com um toque que comecei ou terminei um bloco, sem usar timer.'],
  ['US-EXEC-003','exec','nova','Quero registrar uma atividade fora do plano (troca rápida) sem mexer no plano.'],
  ['US-EXEC-004','exec','nova','Quero um aviso discreto e opcional quando um bloco termina ou o próximo começa.'],
  ['US-EXEC-005','exec','derivada','Quero acessar qualquer ação pelo ⌘K e por atalhos de teclado.'],

  ['US-TASK-001','task','spec','Quero capturar uma tarefa em segundos, sem preencher metadados.'],
  ['US-TASK-002','task','spec','Quero depois enriquecer tarefas com categoria, Life Area, prioridade, estimativa, prazo, tags, projeto e subtarefas.'],
  ['US-TASK-003','task','spec','Quero que tarefas existam independentemente dos blocos.'],
  ['US-TASK-004','task','spec','Quero que uma tarefa mantenha todo o histórico ao ser movida entre dias ou blocos.'],
  ['US-TASK-005','task','spec','Quero que tarefas incompletas voltem ao Backlog em vez de irem sozinhas para amanhã.'],
  ['US-TASK-006','task','spec','Quero que tarefas já iniciadas apareçam em destaque nos próximos planejamentos.'],
  ['US-TASK-007','task','nova','Quero fazer a triagem do Inbox rapidamente, com teclado.'],
  ['US-TASK-008','task','nova','Quero tarefas recorrentes (ex.: “Praticar violão” diário) sem criar duplicatas manualmente.'],
  ['US-TASK-009','task','derivada','Quero buscar e filtrar tarefas por prioridade, área, projeto, tag e prazo.'],
  ['US-TASK-010','task','nova','Quero arquivar ou excluir tarefas que não fazem mais sentido.'],
  ['US-TASK-011','task','nova','Quero ver o histórico completo de uma tarefa: sessões, tempo por dia e blocos em que esteve.'],

  ['US-TIME-001','time','spec','Quero rastrear trabalho focado com sessões configuráveis estilo Pomodoro.'],
  ['US-TIME-002','time','spec','Quero manter uma tarefa aberta depois de várias sessões.'],
  ['US-TIME-003','time','spec','Quero usar um cronômetro simples quando Pomodoro não faz sentido.'],
  ['US-TIME-004','time','spec','Quero registrar depois o que fiz quando esqueci de rastrear ao vivo.'],
  ['US-TIME-005','time','spec','Quero editar registros de tempo históricos.'],
  ['US-TIME-006','time','spec','Quero comparar a duração estimada da tarefa com a duração real acumulada.'],
  ['US-TIME-007','time','nova','Quero corrigir facilmente um timer que esqueci ligado.'],
  ['US-TIME-008','time','nova','Quero transformar o plano em registro real com um clique quando o dia aconteceu como planejado.'],

  ['US-REPLAN-001','replan','spec','Quero mover atividades flexíveis quando surgem compromissos inesperados.'],
  ['US-REPLAN-002','replan','spec','Quero que o dia original fique preservado depois de replanejar.'],
  ['US-REPLAN-003','replan','spec','Quero ver como o plano evoluiu durante o dia.'],
  ['US-REPLAN-004','replan','spec','Quero ajuda opcional para reorganizar os blocos flexíveis restantes.'],
  ['US-REPLAN-005','replan','nova','Quero registrar, se eu quiser, o motivo de uma mudança de plano.'],

  ['US-REVIEW-001','review','spec','Quero comparar o plano com o que realmente aconteceu.'],
  ['US-REVIEW-002','review','spec','Quero reparar lacunas na minha linha do tempo real antes de fechar o dia.'],
  ['US-REVIEW-003','review','spec','Quero que tarefas inacabadas voltem ao Backlog automaticamente.'],
  ['US-REVIEW-004','review','spec','Quero um resumo rápido de como meu tempo foi distribuído.'],
  ['US-REVIEW-005','review','spec','Quero reabrir um dia passado e corrigi-lo.'],
  ['US-REVIEW-006','review','nova','Quando esqueço de fechar o dia, quero resolver isso rápido ao abrir o app no dia seguinte.'],
  ['US-REVIEW-007','review','derivada','Quero registrar uma reflexão curta (nota, energia) sem que isso bloqueie o fechamento.'],

  ['US-CAL-001','cal','spec','Quero ver eventos do Google e do Microsoft enquanto planejo.'],
  ['US-CAL-002','cal','spec','Quero que eventos da família compartilhados sejam Awareness quando não exigem meu tempo.'],
  ['US-CAL-003','cal','spec','Quero que reuniões de trabalho bloqueiem minha timeline.'],
  ['US-CAL-004','cal','spec','Quero publicar blocos selecionados como Busy no calendário do trabalho.'],
  ['US-CAL-005','cal','spec','Quero escolher se um bloco é interno, Google, Microsoft ou ambos.'],
  ['US-CAL-006','cal','spec','Quero que reuniões novas gerem conflitos claros com meu plano atual.'],
  ['US-CAL-007','cal','nova','Quero que cancelamentos e mudanças de eventos externos depois do início do dia atualizem o plano e gerem revisão.'],
  ['US-CAL-008','cal','derivada','Quero mudar a classificação de um evento específico (ex.: Awareness → Commitment).'],
  ['US-CAL-009','cal','derivada','Quero ver o status e os erros de sincronização dos calendários.'],

  ['US-STATS-001','stats','spec','Quero saber quanto tempo passo em cada Life Area.'],
  ['US-STATS-002','stats','spec','Quero comparar tempo planejado e real.'],
  ['US-STATS-003','stats','spec','Quero saber quais categorias de tarefa eu subestimo com frequência.'],
  ['US-STATS-004','stats','spec','Quero ver a distribuição do tempo por semana e por mês.'],
  ['US-STATS-005','stats','spec','Quero entender o formato típico do meu dia.'],
  ['US-STATS-006','stats','spec','Quero que os dados históricos sejam preservados para novas análises no futuro.'],
  ['US-STATS-007','stats','nova','Quero comparar semanas e meses entre si (esta semana × a passada).'],
  ['US-STATS-008','stats','nova','Quero definir metas semanais por Life Area e ver o progresso sem julgamento.'],

  ['US-SET-001','set','derivada','Quero editar os templates Weekday e Weekend.'],
  ['US-SET-002','set','derivada','Quero configurar Life Areas (nome, cor, ícone, meta).'],
  ['US-SET-003','set','derivada','Quero configurar os presets de foco.'],
  ['US-SET-004','set','derivada','Quero exportar todos os meus dados (JSON/CSV).'],
  ['US-SET-005','set','nova','Quero alternar entre tema escuro e claro.'],

  ['US-OFFLINE-001','offline','spec','Quero que o Hoje continue usável sem internet.'],
  ['US-OFFLINE-002','offline','spec','Quero criar e editar tarefas offline.'],
  ['US-OFFLINE-003','offline','spec','Quero rastrear tempo offline.'],
  ['US-OFFLINE-004','offline','spec','Quero que as mudanças sincronizem automaticamente quando a conexão voltar.'],
  ['US-OFFLINE-005','offline','nova','Quero ver claramente quando estou offline e quando tudo foi sincronizado.'],
  ['US-OFFLINE-006','offline','nova','Quero ver no celular um timer que iniciei no desktop (e vice-versa).'],

  ['US-SYS-001','sys','nova','Quero que atividades que atravessam a meia-noite fiquem no dia certo, sem serem cortadas.'],
  ['US-SYS-002','sys','nova','Quero que só uma atividade fique ativa por vez, para o real nunca ter sobreposição acidental.'],

  ['US-WIDGET-001','widget','spec','Quero ver o bloco atual e o próximo sem abrir o app.'],
  ['US-WIDGET-002','widget','spec','Quero um widget com minha lista de tarefas.'],
  ['US-WIDGET-003','widget','spec','Quero um widget compacto com a timeline.'],
  ['US-WIDGET-004','widget','spec','Quero, no futuro, ver o momento atual na tela de bloqueio e no Always-On Display, onde a plataforma permitir.'],
],

/* ───────────────────────── O que dá para fazer ───────────────────────── */
caps: [
  { id:'CAP-A', area:'Acesso e app', items:[
    ['CAP-A1','Entrar com código privado','Tela de acesso, uma vez por dispositivo','MVP'],
    ['CAP-A2','Instalar como app (PWA)','Navegador / sugestão no onboarding','MVP'],
    ['CAP-A3','Usar sem internet','Hoje e Tarefas em cache local','MVP'],
    ['CAP-A4','Ver status de sincronização','Indicador no topo','MVP'],
    ['CAP-A5','Alternar tema claro / escuro','Configurações › Exibição','Proposta'],
    ['CAP-A6','Executar qualquer ação por comando','⌘K (command palette)','MVP'],
  ]},
  { id:'CAP-B', area:'Planejar o dia', items:[
    ['CAP-B1','Abrir o Hoje com o dia já preparado','Hoje › Não planejado','MVP'],
    ['CAP-B2','Escolher modo detalhado ou rápido','Planejar meu dia / Modo rápido','MVP'],
    ['CAP-B3','Revisar contexto (compromissos, awareness, em andamento, prazos, Inbox)','Etapa 1','MVP'],
    ['CAP-B4','Trocar o template do dia','Etapa 2 › menu do template','Proposta'],
    ['CAP-B5','Aceitar, mover, redimensionar, excluir ou substituir blocos','Etapa 2, arrastando','MVP'],
    ['CAP-B6','Adicionar bloco (rotina, fixo, flexível, aberto, deslocamento)','Tecla B, clique em horário vazio, +','MVP'],
    ['CAP-B7','Marcar bloco como Fixo ou Flexível','Inspector do bloco','MVP'],
    ['CAP-B8','Alocar tarefa em bloco','Arrastar do painel de tarefas','MVP'],
    ['CAP-B9','Criar bloco a partir de uma tarefa','Arrastar tarefa para horário vazio','MVP'],
    ['CAP-B10','Ver carga × capacidade de cada bloco','Cabeçalho do bloco','MVP'],
    ['CAP-B11','Resolver conflitos e excessos','Etapa 4','MVP'],
    ['CAP-B12','Iniciar o dia (cria o Baseline)','INICIAR DIA','MVP'],
    ['CAP-B13','Iniciar a partir de agora (dia começado tarde)','Hoje › Não planejado','Proposta'],
    ['CAP-B14','Planejar amanhã','Depois de fechar o dia','Proposta'],
  ]},
  { id:'CAP-C', area:'Executar o dia', items:[
    ['CAP-C1','Ver Agora, Próximo e a timeline com a linha NOW','Hoje › Ativo','MVP'],
    ['CAP-C2','Marcar “comecei” / “terminei” num bloco','Card Agora','Proposta'],
    ['CAP-C3','Iniciar sessão de foco numa tarefa','▶ na tarefa, ⌘K','MVP'],
    ['CAP-C4','Pausar, retomar, parar e finalizar sessão','Timer','MVP'],
    ['CAP-C5','Concluir tarefa','Checkbox, timer','MVP'],
    ['CAP-C6','Iniciar atividade fora do plano','⌘K › Iniciar atividade','Proposta'],
    ['CAP-C7','Capturar tarefa rápida','⌘K, tecla N, +','MVP'],
    ['CAP-C8','Ver detalhes de bloco ou tarefa','Clique → Inspector','MVP'],
  ]},
  { id:'CAP-D', area:'Replanejar', items:[
    ['CAP-D1','Mover, encurtar ou remover bloco depois de iniciar o dia','Arrastar na timeline','MVP'],
    ['CAP-D2','Resolver conflito de reunião nova','Banner de conflito','Fase 2'],
    ['CAP-D3','Replanejar o restante do dia (proposta automática)','⌘K › Replanejar','A definir'],
    ['CAP-D4','Ver o histórico de revisões','Inspector › Histórico','MVP'],
    ['CAP-D5','Informar o motivo da mudança','Campo opcional na revisão','Proposta'],
  ]},
  { id:'CAP-E', area:'Tarefas', items:[
    ['CAP-E1','Ver Inbox, Em andamento, Backlog e Concluídas','Tarefas','MVP'],
    ['CAP-E2','Fazer triagem do Inbox','Tarefas › Inbox, com atalhos','MVP'],
    ['CAP-E3','Editar campos (área, prioridade, estimativa, prazo, tags, projeto, categoria, Work/Personal)','Detalhe da tarefa','MVP'],
    ['CAP-E4','Subtarefas e notas','Detalhe da tarefa','MVP'],
    ['CAP-E5','Recorrência','Detalhe da tarefa','A definir'],
    ['CAP-E6','Filtrar e buscar','Barra de filtros + gaveta avançada','MVP'],
    ['CAP-E7','Desagendar (voltar ao Backlog)','Arrastar para o Backlog','MVP'],
    ['CAP-E8','Arquivar ou excluir','Menu contextual','MVP'],
    ['CAP-E9','Ver o histórico da tarefa (sessões, tempo, blocos)','Detalhe › Histórico','MVP'],
  ]},
  { id:'CAP-F', area:'Registrar o real', items:[
    ['CAP-F1','Rastrear ao vivo (iniciar / parar)','Hoje','MVP'],
    ['CAP-F2','Registrar tempo passado','⌘K › Registrar tempo passado','MVP'],
    ['CAP-F3','Editar, redimensionar ou remover registro','Timeline Real','MVP'],
    ['CAP-F4','Mudar a Life Area ou associar uma tarefa depois','Inspector do registro','MVP'],
    ['CAP-F5','Adicionar, editar ou excluir sessão de foco','Detalhe da tarefa','MVP'],
    ['CAP-F6','Corrigir timer esquecido ligado','Aviso ao voltar ao app','Proposta'],
    ['CAP-F7','Transformar o plano em real com um clique','Fechar dia › Passo 1','Proposta'],
  ]},
  { id:'CAP-G', area:'Fechar o dia', items:[
    ['CAP-G1','Reparar lacunas e sobreposições','Passo 1','MVP'],
    ['CAP-G2','Revisar tarefas (concluídas, em andamento, não iniciadas)','Passo 2','MVP'],
    ['CAP-G3','Reflexão opcional (nota, energia, algo incomum)','Passo 3','MVP'],
    ['CAP-G4','Ver o resumo e fechar','Passo 4','MVP'],
    ['CAP-G5','Reabrir o dia','Hoje fechado ou Histórico','MVP'],
    ['CAP-G6','Fechar ontem ao abrir hoje','Cartão no Hoje','Proposta'],
  ]},
  { id:'CAP-H', area:'Histórico', items:[
    ['CAP-H1','Navegar por calendário ou lista','Histórico','MVP'],
    ['CAP-H2','Abrir um dia: Baseline, Final, Real, Tarefas, Stats, Revisões','Detalhe do dia','MVP'],
    ['CAP-H3','Editar dias passados','Detalhe › Real','MVP'],
  ]},
  { id:'CAP-I', area:'Insights', items:[
    ['CAP-I1','Distribuição por Life Area, categoria, projeto, tarefa','Insights','MVP básico'],
    ['CAP-I2','Planejado × real (3 modos de comparação)','Insights / Histórico','Fase 3'],
    ['CAP-I3','Precisão das estimativas','Insights › Estimativa','Fase 3'],
    ['CAP-I4','Estatísticas de foco','Insights › Foco','Fase 3'],
    ['CAP-I5','Formato do dia (day shape)','Insights › Formato do dia','Fase 3'],
    ['CAP-I6','Comparar períodos','Insights','Fase 3'],
  ]},
  { id:'CAP-J', area:'Calendários', items:[
    ['CAP-J1','Conectar Google e Microsoft','Configurações › Calendários','Fase 2'],
    ['CAP-J2','Escolher calendários e a classificação padrão','Configurações › Calendários','Fase 2'],
    ['CAP-J3','Mudar a classificação de um evento','Inspector do evento','Fase 2'],
    ['CAP-J4','Publicar bloco como Busy (Google, Microsoft ou ambos)','Inspector do bloco','Fase 2'],
    ['CAP-J5','Excluir bloco publicado (só aqui / aqui + externo)','Diálogo de exclusão','Fase 2'],
    ['CAP-J6','Ver erros de sincronização','Configurações › Sync','Fase 2'],
  ]},
  { id:'CAP-K', area:'Configurações e dados', items:[
    ['CAP-K1','Editar templates Weekday e Weekend','Configurações','MVP'],
    ['CAP-K2','Configurar Life Areas','Configurações','MVP'],
    ['CAP-K3','Configurar categorias','Configurações','MVP'],
    ['CAP-K4','Configurar presets de foco','Configurações','MVP'],
    ['CAP-K5','Preferências de notificação','Configurações','MVP'],
    ['CAP-K6','Preferências de exibição','Configurações','MVP'],
    ['CAP-K7','Exportar dados','Configurações','MVP'],
    ['CAP-K8','Ver ou limpar analytics de produto','Configurações','MVP'],
  ]},
  { id:'CAP-L', area:'Fora do app (futuro)', items:[
    ['CAP-L1','Widgets Android: bloco atual, timeline, tarefas, próximas tarefas, progresso','Tela inicial','Fase 5'],
    ['CAP-L2','Tela de bloqueio e Always-On Display','Android','Fase 5+'],
    ['CAP-L3','Wear OS: complicação, tile e app','Relógio','Fase 6'],
    ['CAP-L4','Gamificação estilo floresta','A definir','Fase 7'],
  ]},
],

/* ───────────────────────── Telas e estados ───────────────────────── */
screens: [
  { id:'SCR-ACCESS', name:'Acesso', purpose:'Entrar com o código privado.', states:['Código','Erro','Dispositivo já pareado (pula a tela)'], actions:['Entrar'] },
  { id:'SCR-TODAY-0', name:'Hoje · Não planejado', purpose:'Receber o dia já preparado e escolher como planejar.', states:['Primeira visita do dia','Ontem não fechado (cartão)','Início tardio'], actions:['Planejar meu dia','Modo rápido','Iniciar a partir de agora'] },
  { id:'SCR-TODAY-PLAN', name:'Hoje · Planejamento', purpose:'As 4 etapas numa tela de 3 colunas: Tarefas | Timeline | Inspector.', states:['Etapa 1 Contexto (com ações)','Etapa 2 Montar o dia','Etapa 3 Conflitos','Etapa 4 Iniciar'], actions:['Avançar ou pular etapas','Arrastar','INICIAR DIA'] },
  { id:'SCR-TODAY-ACTIVE', name:'Hoje · Ativo', purpose:'Execução: Agora, Próximo e a timeline com a linha NOW.', states:['Sem atividade ativa','Bloco em andamento','Timer rodando','Conflito pendente','Offline'], actions:['Comecei / Terminei','▶ Foco','Replanejar','Fechar dia'] },
  { id:'SCR-TODAY-CLOSE', name:'Hoje · Fechamento', purpose:'Os 4 passos do fim do dia.', states:['1 Reparar real','2 Tarefas','3 Reflexão','4 Resumo'], actions:['Preencher lacuna','Aceitar plano como real','Pular','Fechar dia'] },
  { id:'SCR-TODAY-CLOSED', name:'Hoje · Fechado', purpose:'Resumo do dia.', states:['Fechado','Fechado automaticamente'], actions:['Reabrir','Planejar amanhã (proposta)'] },
  { id:'SCR-TASKS', name:'Tarefas', purpose:'Inbox, Em andamento, Backlog, Concluídas.', states:['Lista','Filtros ativos','Detalhe aberto à direita'], actions:['Triar','Filtrar','Agendar','Arquivar'] },
  { id:'SCR-TASK-DETAIL', name:'Detalhe da tarefa', purpose:'Campos com revelação progressiva, histórico e sessões.', states:['Resumo','Expandido','Histórico'], actions:['Editar','Iniciar foco','Concluir','Editar sessões'] },
  { id:'SCR-HISTORY', name:'Histórico', purpose:'Entender e corrigir dias passados.', states:['Calendário','Lista','Detalhe do dia (Baseline / Final / Real / Tarefas / Stats / Revisões)'], actions:['Abrir dia','Editar real','Reabrir'] },
  { id:'SCR-INSIGHTS', name:'Insights', purpose:'Visão geral, Áreas, Planejado × Real, Estimativa, Foco, Formato do dia, Tarefas.', states:['Hoje','Semana','Mês','Período'], actions:['Trocar período','Comparar'] },
  { id:'SCR-SETTINGS', name:'Configurações', purpose:'Templates, áreas, categorias, presets, calendários, notificações, exibição, sync, exportar, analytics.', states:['Lista de seções'], actions:['Editar'] },
  { id:'SCR-PALETTE', name:'Command palette (⌘K)', purpose:'Qualquer ação sem menus.', states:['Vazio (sugestões)','Buscando','Executando'], actions:['Nova tarefa','Adicionar bloco','Iniciar timer','Registrar tempo passado','Ir para Hoje','Replanejar','Fechar dia'] },
  { id:'SCR-QUICKADD', name:'Adição rápida (+)', purpose:'Tarefa, Bloco, Registro de tempo, Item de Inbox, com padrão pelo contexto.', states:['Tarefas → Tarefa','Timeline → Bloco'], actions:['Criar'] },
  { id:'SCR-CONFLICT', name:'Resolução de conflito', purpose:'Inline ou banner, nunca modal bloqueante.', states:['Planejamento','Dia ativo (reunião nova)'], actions:['Manter','Mover','Encurtar','Remover','Replanejar restante'] },
  { id:'SCR-MOBILE', name:'Mobile (PWA)', purpose:'Hoje, Tarefas, Histórico, Mais. Prioriza Agora, Próximo e Timeline.', states:['Bottom sheets','Cards expansíveis'], actions:['Captura rápida','Comecei / Terminei','Fechar dia'] },
],

/* ───────────────────────── Regras e ciclos de vida ───────────────────────── */
rules: [
  { id:'RUL-DAY', name:'Ciclo de vida do Dia', chain:['Não planejado','Planejando','Ativo','Fechando','Fechado'], back:'Fechado → Reaberto → Ativo',
    rules:['INICIAR DIA salva o Baseline (imutável).','Toda mudança depois do início gera uma Plan Revision.','Fechar dia devolve as tarefas não concluídas ao Backlog.','Reabrir é sempre possível. O Baseline nunca muda.','Um dia pode nunca ser iniciado (ver Q-05) ou nunca ser fechado (ver Q-06).'] },
  { id:'RUL-TASK', name:'Ciclo de vida da Tarefa', chain:['Inbox','Backlog','Planned','In Progress','Completed','Archived'],
    rules:['Inbox = capturada, sem triagem. Backlog = conhecida, não agendada.','Planned = ligada a um bloco de hoje.','In Progress = recebeu tempo (sessão ou registro).','No fim do dia: Planned / In Progress não concluídas → Backlog, com histórico.','Nunca vai sozinha para amanhã.','Finalizar sessão ≠ concluir tarefa.'] },
  { id:'RUL-BLOCK', name:'Tipos de Bloco', chain:['Rotina','Fixo','Flexível','Calendário','Aberto','Deslocamento'],
    rules:['Rotina vem do template e pode ser substituída só no dia.','Fixo não se move no replanejamento automático.','Flexível pode ser movido pelo replanejamento.','Calendário é do provedor e não é movido pelo DailyFlow.','Aberto não exige tarefa, destino nem timer.','Deslocamento é manual e sugere descrições recentes.'] },
  { id:'RUL-FOCUS', name:'Sessão de foco', chain:['Rodando','Pausada','Pausa (break)','Finalizada'], back:'Rodando → Interrompida · Descartada',
    rules:['Presets 25/5, 30/5, 45/10, 50/10, 60/10, livre, cronômetro.','Uma tarefa acumula quantas sessões forem precisas.','Pausa não conta como foco.','Sessões podem ser adicionadas, editadas e excluídas depois.'] },
  { id:'RUL-EVENT', name:'Evento externo', chain:['Commitment','Awareness','Optional'],
    rules:['Commitment bloqueia a timeline.','Awareness aparece no contexto e não ocupa tempo.','Optional não bloqueia, mas pode virar Commitment.','Padrão por calendário, com exceção por evento.','Eventos importados continuam do provedor. O DailyFlow só edita os que ele mesmo criou.'] },
  { id:'RUL-RECORD', name:'Registro de tempo (Time Record)', chain:['FOCUS_TIMER','LIVE_MANUAL','HISTORICAL_MANUAL','IMPORT','SYSTEM'],
    rules:['Toda forma de rastreio vira o mesmo registro normalizado.','A edição histórica marca historically_edited_at.','O registro pode ter tarefa, bloco e sessão, todos opcionais. A área é obrigatória.','Proposta: só um registro ativo por vez (US-SYS-002).'] },
  { id:'RUL-LAYERS', name:'Três camadas do dia', chain:['Baseline','Plano atual / final','Real'],
    rules:['Baseline = o plano aceito no início do dia. Imutável.','Plano atual = última intenção, reconstruível revisão a revisão.','Real = o que aconteceu (ao vivo, timer ou depois).','Comparações: Baseline × Real, Final × Real, Baseline × Final.'] },
],

/* ───────────────────────── Roadmap ───────────────────────── */
phases: [
  { id:'PH-1', name:'Fase 1 · Web/PWA core (MVP)', scope:['Templates Weekday/Weekend','Hoje com planejamento em etapas','Timeline e blocos','Inbox, Backlog, agendamento e detalhe de tarefa','Timer de foco','Registros de tempo reais e edição histórica','Separação Baseline / Atual / Real','Histórico básico','Cache offline e sync básico','Estatísticas básicas'], out:['Android, widgets, Wear OS','Gamificação','Planejamento por IA','Replanejamento automático avançado'] },
  { id:'PH-2', name:'Fase 2 · Calendários', scope:['Google Calendar (vários calendários)','Classificação Awareness / Commitment','Calendário de trabalho Microsoft','Conflitos com reuniões externas','Publicar blocos Busy','Sync incremental','Status e erros de sync'], out:[] },
  { id:'PH-3', name:'Fase 3 · Analytics', scope:['Planejado × Real','Distribuição por Life Area','Precisão de estimativas','Estatísticas de foco','Visões semanal e mensal','Formato do dia','Analytics de replanejamento'], out:[] },
  { id:'PH-4', name:'Fase 4 · App Android', scope:['Hoje nativo/mobile','Tarefas','Timer de foco','Edição histórica','Sync offline-first','Notificações','Infraestrutura de widgets'], out:[] },
  { id:'PH-5', name:'Fase 5 · Widgets Android', scope:['Bloco atual','Timeline','Tarefas','Próximas tarefas','Progresso do dia','Investigar tela de bloqueio e AOD'], out:[] },
  { id:'PH-6', name:'Fase 6 · Wear OS', scope:['Complicação','Tile','App mínimo','App mais completo','Experimentos de watch face'], out:[] },
  { id:'PH-7', name:'Fase 7 · Gamificação', scope:['Floresta por Life Area','Espécies desbloqueáveis','Histórico visual de longo prazo','Sem punição por replanejar ou descansar'], out:[] },
],

/* ───────────────────────── Perguntas abertas ───────────────────────── */
questionTopics: [['marca','Marca e idioma'],['dia','Ciclo do dia'],['real','Real e rastreio'],['tarefas','Tarefas'],['escopo','Escopo e fases'],['sistema','Sistema e dados']],
questions: [
  { id:'Q-01', topic:'marca', q:'Renomeio “Daily OS” para “DailyFlow” em toda a spec, inclusive no modelo de dados e nos eventos de analytics?', rec:'Sim, em tudo. Os termos internos (Baseline, Plan Revision, Time Record) continuam como estão.' },
  { id:'Q-02', topic:'marca', q:'Qual será o idioma da interface?', ctx:'A spec está em inglês e os termos-chave são “Today”, “Start Day”, “Backlog”, “Inbox”.', opts:['Só português','Só inglês','Português com termos-chave em inglês','Bilíngue (i18n desde o início)'], rec:'Interface em inglês, que combina com a spec, os nomes do código e o analytics. i18n fica preparado, mas não é traduzido no MVP. Se preferir PT-BR, decidir agora, antes dos wireframes.' },
  { id:'Q-03', topic:'real', q:'Se eu não rastrear nada, o plano pode virar o real com um clique no fechamento?', ctx:'É o maior redutor de atrito para a Jornada D. Sem isso, reconstruir o dia vira bookkeeping.', opts:['Sim, botão “Aceitar plano final como real”','Sim, e automático ao fechar','Não, o real é sempre explícito'], rec:'Botão explícito no Passo 1. Nunca automático, para o dado continuar honesto.' },
  { id:'Q-04', topic:'dia', q:'Onde um dia começa e termina?', ctx:'O template tem “21:00 em diante: Leitura / Sono”. Sono, filmes e voos cruzam a meia-noite.', opts:['Meia-noite','Virada configurável (ex.: 04:00)','O dia termina quando eu fecho'], rec:'Virada configurável, padrão 04:00. O sono é registrado no dia em que começou.' },
  { id:'Q-05', topic:'dia', q:'E se eu nunca clicar INICIAR DIA?', ctx:'Fim de semana e dias corridos. Sem Baseline, o Planejado × Real daquele dia fica vazio.', opts:['Sem Baseline naquele dia','Baseline implícito na primeira ação de execução (timer, Comecei)','Baseline implícito num horário fixo'], rec:'Baseline implícito na primeira ação de execução, marcado como “implícito” para os Insights poderem filtrar.' },
  { id:'Q-06', topic:'dia', q:'O que acontece com um dia que nunca foi fechado?', opts:['Fica aberto para sempre','Cartão no dia seguinte (fechar agora / automático / depois)','Fecha sozinho à meia-noite'], rec:'Cartão no dia seguinte (F-13). Depois de N dias, fecha automaticamente em silêncio.' },
  { id:'Q-07', topic:'dia', q:'Ao iniciar o dia tarde, os blocos que já passaram entram no Baseline?', rec:'Não. O Baseline começa em “agora” e fica marcado como início tardio. Os blocos passados viram candidatos a real.' },
  { id:'Q-08', topic:'dia', q:'Posso planejar amanhã na noite anterior?', ctx:'A spec só cobre o planejamento de manhã.', rec:'Sim, opcional, na tela de dia fechado. De manhã o plano aparece pronto e o INICIAR DIA continua sendo de manhã.' },
  { id:'Q-09', topic:'tarefas', q:'Como funcionam tarefas recorrentes?', ctx:'Recorrência é campo opcional na spec, mas o comportamento não está definido.', opts:['Uma instância nova por ocorrência','Uma tarefa só, que “reabre”','Recorrência é do bloco, não da tarefa'], rec:'Uma instância por ocorrência, que aparece no contexto do dia sem ser agendada automaticamente. Para hábitos (violão), talvez baste o bloco do template.' },
  { id:'Q-10', topic:'real', q:'Uma sessão de foco que atravessa o fim do bloco pertence a qual bloco?', rec:'O registro pertence à tarefa. O bloco é deduzido pela sobreposição de horário e o registro não é cortado.' },
  { id:'Q-11', topic:'real', q:'Pode haver duas atividades ativas ao mesmo tempo (timer + registro ao vivo)?', rec:'Não. Uma por vez: iniciar outra encerra a anterior. Isso evita sobreposição acidental no real.' },
  { id:'Q-12', topic:'real', q:'Se uma tarefa de área Work está dentro de um bloco Maker, o tempo vai para qual área?', rec:'Para a área da tarefa. Sem tarefa, para a área do bloco.' },
  { id:'Q-13', topic:'tarefas', q:'O campo Work/Personal é redundante com a Life Area?', ctx:'A spec exige os dois.', rec:'Derivar Work/Personal da Life Area (Work → Work, resto → Personal), com exceção manual.' },
  { id:'Q-14', topic:'tarefas', q:'Prioridade é obrigatória, mas a captura não pede nada. Qual é o padrão?', opts:['Medium','“Sem prioridade” até a triagem'], rec:'“Sem prioridade” no Inbox. Obrigatória só na triagem para o Backlog.' },
  { id:'Q-15', topic:'tarefas', q:'Quando um item sai do Inbox para o Backlog?', rec:'Na triagem explícita (F-12) ou ao ser agendado. A Etapa 1 do planejamento mostra o Inbox só como contexto.' },
  { id:'Q-16', topic:'tarefas', q:'O app deve sugerir uma nova estimativa quando a tarefa estoura?', rec:'Na Fase 3, mostrar a estimativa ajustada pelo multiplicador histórico como dica, nunca aplicada sozinha.' },
  { id:'Q-17', topic:'tarefas', q:'Posso agendar uma tarefa para um dia futuro específico (ex.: sexta)?', ctx:'A spec só fala em Hoje e Backlog.', rec:'Sim, como “data sugerida”: a tarefa aparece no contexto daquele dia, sem ser alocada automaticamente.' },
  { id:'Q-18', topic:'sistema', q:'Quais notificações existem no PWA?', ctx:'A spec quer silêncio e um status contínuo.', rec:'Só o fim do timer (som + notificação) por padrão. Transição de bloco é opcional e vem desligada.' },
  { id:'Q-19', topic:'escopo', q:'“Replanejar restante do dia” entra no MVP?', ctx:'A Fase 1 exclui o “replanejamento automático avançado”, mas a Jornada A usa replanejamento.', rec:'MVP: só ações manuais (mover, encurtar, remover). Replanejar restante (determinístico) numa Fase 1.5.' },
  { id:'Q-20', topic:'escopo', q:'Os calendários são Fase 2, mas as jornadas assumem calendários. Como é o MVP sem eles?', rec:'No MVP, compromissos entram como blocos Fixos manuais. A Etapa 1 mostra só tarefas e template.' },
  { id:'Q-21', topic:'escopo', q:'Entra uma revisão semanal (F-21) no produto?', rec:'Não como fluxo guiado. Os Insights semanais bastam, e o uso real decide depois.' },
  { id:'Q-22', topic:'dia', q:'Editar um dia fechado exige reabrir antes?', rec:'Não. Edições no Histórico são livres. “Reabrir” existe só para refazer o fechamento.' },
  { id:'Q-23', topic:'dia', q:'Posso salvar o dia de hoje como novo template?', rec:'Sim, ação explícita com confirmação mostrando as diferenças.' },
  { id:'Q-24', topic:'dia', q:'Blocos Abertos aceitam tarefas?', rec:'Sim, mas sem mostrar capacidade. Se receber tarefa, o bloco continua Aberto.' },
  { id:'Q-25', topic:'dia', q:'Na montagem do esqueleto, uma reunião que cai sobre um bloco do template encolhe o bloco sozinha?', rec:'Não. Sinaliza na Etapa 4 com a sugestão pronta (“encurtar Work para 10:30–11:00”) e aplica com um clique.' },
  { id:'Q-26', topic:'real', q:'Qual é a escala do nível de energia na reflexão?', rec:'1 a 5, opcional. Sem emojis.' },
  { id:'Q-27', topic:'sistema', q:'Em que formato é a exportação de dados?', rec:'JSON completo (backup) + CSV de registros de tempo (para análise externa).' },
  { id:'Q-28', topic:'sistema', q:'Fuso horário e viagens entram agora?', rec:'Guardar UTC + fuso por dia desde o início. A interface para viagens fica para depois.' },
  { id:'Q-29', topic:'sistema', q:'Analytics de produto: tabela própria ou ferramenta externa (PostHog)?', rec:'Tabela própria (product_events), como a spec sugere. É single-user e os dados ficam com você.' },
  { id:'Q-30', topic:'sistema', q:'Um timer rodando aparece em todos os dispositivos?', rec:'Sim. O timer é estado do servidor (início + pausas), não um contador local.' },
],

/* ───────────────────────── Respostas às revisões ───────────────────────── */
replies: {
  'E1.f5':'As 11 da spec: Work, Music, Physical Activity, Family, Maker, FlightSim, Rest, Leisure, Commute, Personal e Sleep. Sim, editáveis desde a E1: renomear, trocar cor e ícone, adicionar e arquivar (arquivar em vez de excluir, para não quebrar o histórico).',
  'VIS-CAMADAS':'Entrou “O que mudou hoje” (E2): no fim do dia, uma lista em linguagem simples, ordenada pelo tamanho da diferença (“Work +1h10 além do plano”, “FlightSim não aconteceu”, “Music começou 8 min depois”), e na timeline cada bloco real ganha um selo com a diferença. Não precisa comparar duas colunas.',
  'DIA-03':'Você tem razão: blocos e tarefas precisam ser decididos juntos. O planejamento passou de 5 para 4 etapas: o Contexto ganhou ações (“Para hoje” nas tarefas, “+ Compromisso”) e Esqueleto + Alocar viraram uma etapa só, “Montar o dia”, com os blocos e as tarefas marcadas na mesma tela.',
  'DIA-04':'(1) Durante o planejamento: N (ou ⌘K) captura a tarefa e ela aparece no painel pronta para arrastar; compromisso novo é um clique num horário vazio. (2) Sim, toda tarefa tem Life Area (o ponto colorido). Ao arrastar, os blocos da mesma área se destacam; soltar uma tarefa Maker num bloco Work mostra um aviso leve com “Mover para Maker” ou “Manter”. Entrou na E4 e na E5.',
  'Q-01':'Decidido: aplicado na spec (daily-os-product-functional-spec.md agora diz DailyFlow).',
  'Q-02':'Decidido: interface em inglês, com i18n preparado. Os wireframes desta revisão continuam em português só para facilitar a leitura.',
  'E0':'Removida. A fundação (PWA, acesso, banco local, log de eventos, check-in) virou o Passo 0 da E1, sem validação própria.',
},

/* ───────────────────────── Design system (itens revisáveis) ───────────────────────── */
design: [
  ['DS-DARK','Tema escuro (base definida por você)'],
  ['DS-LIGHT','Tema claro (proposta v0.1)'],
  ['DS-TRANSITION','Transição entre temas'],
  ['DS-PILLS','Pills de blocos e eventos por Life Area'],
  ['DS-TODAY','Mock do Hoje ativo (Agora · Próximo · Timeline)'],
],
};
