/* DailyFlow — etapas de desenvolvimento e validação.
 * Cada etapa é usável no dia a dia, responde uma pergunta sobre o framework
 * e só junta funcionalidades que fazem sentido juntas.
 * refs apontam para itens da revisão (CAP-*, US-*, Q-*, F-*).
 */
const STAGE_WAVES = [
  ['w1', 'Onda 1 · Núcleo do framework', 'blue'],
  ['w2', 'Onda 2 · Tarefas e ritual', 'purple'],
  ['w3', 'Onda 3 · Ciclo completo e mobilidade', 'orange'],
  ['w4', 'Onda 4 · Mundo externo', 'cyan'],
  ['w5', 'Onda 5 · Aprender e refinar', 'green'],
  ['wh', 'Horizonte', 'gray'],
];

const STAGES = [
  { id: 'E1', name: 'O dia em blocos', short: 'Dia em blocos', wave: 'w1', pri: 'P0', deps: [], dur: '1 semana', icon: 'calendar', state: 'aprovada',
    setup: [
      ['zap', 'App web/PWA instalável no desktop e no celular, com o design system, temas e a transição em círculo'],
      ['lock', 'Acesso por código privado; o dispositivo fica confiável e não pede login de novo'],
      ['database', 'Banco local (IndexedDB) com sincronização básica com o servidor: a base do offline-first'],
      ['layers', 'Registro de eventos de produto em toda interação (sessão, dispositivo, tela, etapa)'],
      ['help', 'Check-in de validação dentro do app, com respostas salvas como eventos'],
      ['download', 'Tela Dados de validação: ver e exportar eventos (JSON / CSV)'],
      ['msg', 'Notes: comentários sobre o app com número (#1, #2…), estados (aberta, em discussão, em andamento, feita, ignorada) e registro exato do que o Claude fez, ignorou e decidiu'],
    ],
    nav: ['hoje', 'config'], hero: 's1Today', wf: ['s1Today', 's1Mobile'],
    q: 'Ver o dia como blocos, com Agora e Próximo sempre visíveis, me ajuda a me orientar?',
    why: 'É a hipótese mais básica do produto. Se olhar o dia em blocos não ajuda, nada construído em cima vai ajudar.',
    feats: [
      ['calendar', 'Um template por dia da semana (Seg–Dom), com “Copiar de…”; Seg–Sex partem do Weekday da spec e Sáb/Dom do Weekend; o Hoje escolhe pelo dia (nota #2 do app)', ['CAP-B1', 'US-PLAN-001']],
      ['home', 'Hoje: timeline 06–22 com blocos coloridos por área e a linha NOW', ['CAP-C1']],
      ['play', 'Cards Agora (bloco atual e tempo restante) e Próximo', ['US-EXEC-001']],
      ['move', 'Criar, mover, redimensionar, renomear e excluir blocos só no dia de hoje; o template não muda', ['CAP-B5', 'CAP-B6', 'US-PLAN-002']],
      ['layers', '11 Life Areas padrão com cor, editáveis (renomear, cor, ícone, adicionar, arquivar): Work, Music, Physical Activity, Family, Maker, FlightSim, Rest, Leisure, Commute, Personal, Sleep', ['CAP-K2', 'US-SET-002']],
      ['gear', 'Editor de template (a mesma timeline), com seletor de dia e “Copiar de…”', ['CAP-K1', 'US-SET-001']],
      ['phone', 'Celular: Agora, Próximo e timeline', ['SCR-MOBILE']],
    ],
    not: ['Iniciar dia / Baseline', 'Rastreio do real', 'Tarefas'],
    grow: ['PWA + log de eventos', 'Template por dia da semana', 'Timeline + linha NOW', 'Agora / Próximo', 'Editar blocos do dia', 'Life Areas', 'Hoje no celular'],
    daily: [
      ['Quantas vezes você olhou o Agora/Próximo hoje?', '0 · 1–2 · 3–5 · 6+'],
      ['O dia seguiu o template em linhas gerais?', '1 a 5'],
      ['Algum bloco do template precisou ser corrigido de novo?', 'Sim (qual?) · Não'],
    ],
    retro: [
      ['Você sentiria falta se o app sumisse amanhã?', '1 a 5'],
      ['O Weekday atual representa sua rotina?', '1 a 5'],
      ['Onde você olhou mais: desktop ou celular?', 'Desktop · Celular · Igual'],
    ],
    logs: [
      ['today_opened', 'device, hour, since_last_open_min', 'Com que frequência consulto o dia'],
      ['block_created / block_deleted', 'area, duration_min, from_template', 'O template está certo?'],
      ['block_moved / block_resized', 'delta_min, from_template', 'Quais blocos sempre ajusto'],
      ['template_edited', 'template, change', 'O template converge?'],
    ],
    crit: ['Hoje aberto em pelo menos 5 dos 7 dias', 'Média de 3 ou mais aberturas por dia', '“Sentiria falta” com nota 3 ou mais'],
    fail: 'Rever a densidade da timeline e testar um aviso na troca de bloco (Q-18) antes da E2.' },

  { id: 'E2', name: 'Plano × Real', short: 'Plano × Real', wave: 'w1', pri: 'P0', deps: ['E1'], dur: '1–2 semanas', icon: 'layers', state: 'aprovada',
    nav: ['hoje', 'config'], hero: 's2Active', wf: ['s2Start', 's2Active', 's2Close', 'dayDiff', 'yesterday'],
    q: 'Registrar o que realmente aconteceu é leve o suficiente para eu fazer todo dia?',
    why: 'É o coração do framework: separar plano e realidade. Se registrar o real for pesado, as estatísticas, o histórico e os insights perdem o sentido.',
    feats: [
      ['play', 'Iniciar dia: salva o Baseline (aceitar o template e iniciar, em 1 clique)', ['CAP-B12', 'US-PLAN-008']],
      ['clock', 'Comecei / Terminei em cada bloco, com uma atividade ativa por vez', ['CAP-C2', 'US-EXEC-002', 'US-SYS-002']],
      ['zap', 'Troca rápida: registrar algo fora do plano escolhendo a área', ['CAP-C6', 'US-EXEC-003']],
      ['layers', 'Timeline em modo Plano × Real (duas faixas lado a lado)', ['US-REVIEW-001']],
      ['history', 'Registrar tempo passado e editar registros (arrastar bordas, trocar área)', ['CAP-F2', 'CAP-F3', 'CAP-F4', 'US-TIME-004']],
      ['moon', 'Fechar dia v1: preencher lacunas, “aceitar plano como real” e resumo por área', ['CAP-G1', 'CAP-G4', 'CAP-F7', 'US-TIME-008']],
      ['sunrise', 'Ontem não fechado: cartão simples ao abrir o app', ['CAP-G6', 'US-REVIEW-006']],
      ['moon', 'Virada do dia lógico configurável (padrão 04:00)', ['US-SYS-001', 'Q-04']],
      ['listChecks', 'O que mudou hoje: diferenças entre plano e real em linguagem simples, ordenadas pelo tamanho, e selos de diferença na timeline', ['VIS-CAMADAS', 'US-REVIEW-001']],
    ],
    not: ['Revisões e comparação de planos', 'Tarefas', 'Timer de foco'],
    grow: ['Iniciar dia (Baseline)', 'Comecei / Terminei', 'Troca rápida de atividade', 'Plano × Real na timeline', 'Editar e registrar o passado', 'Fechar dia v1', 'O que mudou hoje'],
    daily: [
      ['O real registrado hoje representa o dia?', '1 a 5'],
      ['Quanto tempo levou para fechar o dia?', '< 1 min · 1–3 · 3–5 · > 5'],
      ['Você registrou ao vivo ou depois?', 'Ao vivo · Misto · Tudo depois'],
    ],
    retro: [
      ['Fechar o dia virou hábito?', '1 a 5'],
      ['O que deu mais trabalho?', 'Lembrar de registrar · Corrigir horários · Escolher área · Nada'],
      ['“Aceitar plano como real” foi usado mais do que o registro ao vivo?', 'Sim · Não'],
    ],
    logs: [
      ['day_started', 'implicit, minutes_after_first_open', 'Iniciar dia faz sentido? (Q-05)'],
      ['block_started / block_finished', 'source (live | close), delay_min', 'Ao vivo ou retroativo?'],
      ['time_record_created / time_record_edited', 'source, duration_min, from_plan, field', 'Onde o real diverge'],
      ['gap_filled', 'method, gap_min', 'Como as lacunas são resolvidas'],
      ['plan_accepted_as_real', 'blocks, edits_after', 'O atalho é usado? (Q-03)'],
      ['day_closed', 'duration_s, tracked_min, gap_min', 'Fechamento é leve?'],
    ],
    crit: ['Dia fechado em 70% ou mais dos dias', 'Fechamento com p50 abaixo de 3 min', 'Real cobrindo 85% ou mais das horas acordadas', 'Nota de fidelidade 4 ou mais'],
    fail: 'Se o fechamento pesa, simplificar: o fechamento vira só “confirmar o plano” + 1 ajuste. Se ninguém usa o registro ao vivo, escondê-lo e apostar no retroativo.' },

  { id: 'E3', name: 'Replanejar sem culpa', short: 'Replanejar', wave: 'w1', pri: 'P0', deps: ['E2'], dur: '1 semana', icon: 'refresh', state: 'aprovada',
    nav: ['hoje', 'config'], hero: 's3Compare', wf: ['s3Conflict', 's3Compare', 'replan'],
    q: 'Mudar o plano durante o dia é simples, e entender o que mudou me ajuda?',
    why: 'A spec trata replanejar como funcionalidade central. As três camadas (Baseline, Final, Real) só mostram valor quando o dia muda.',
    feats: [
      ['history', 'Revisão automática a cada mudança depois de Iniciar dia (mover, encurtar, remover, adicionar)', ['CAP-D1', 'US-REPLAN-002']],
      ['lock', 'Blocos Fixo × Flexível', ['CAP-B7']],
      ['alert', 'Sobreposição detectada com ações: manter, mover, encurtar, remover', ['US-REPLAN-001']],
      ['pencil', 'Motivo opcional da mudança', ['CAP-D5', 'US-REPLAN-005']],
      ['panels', 'Histórico do dia no Inspector: Baseline → R1 → R2…', ['CAP-D4', 'US-REPLAN-003']],
      ['layers', 'Aba Comparar: Baseline × Final × Real', ['US-REVIEW-001']],
    ],
    not: ['Replanejar restante automático (E5)', 'Conflitos com calendários externos (E9)'],
    grow: ['Revisões do plano', 'Fixo × Flexível', 'Detecção de sobreposição', 'Motivo da mudança', 'Comparar Baseline × Final × Real'],
    daily: [
      ['Você mudou o plano hoje? Como foi?', 'Não mudei · Fácil · Chato'],
      ['A comparação explicou algo que você não sabia?', 'Sim · Não · Não olhei'],
    ],
    retro: [
      ['Preencher o motivo vale a pena?', 'Sim · Às vezes · Não'],
      ['Fixo × Flexível foi útil?', '1 a 5'],
    ],
    logs: [
      ['plan_revision_created', 'change_type, reason?, minutes_since_start', 'Quanto e por que o dia muda'],
      ['conflict_detected / conflict_resolved', 'kind, action, ms_to_resolve', 'Qual ação é a padrão'],
      ['compare_viewed', 'mode, dwell_s', 'A comparação é consultada?'],
      ['revision_history_opened', 'revisions_count', 'O histórico interessa?'],
    ],
    crit: ['Toda mudança depois do início gera revisão (nenhuma perdida no log)', 'Replanejar com p50 de 3 cliques ou menos', 'Comparação aberta em pelo menos 2 dias'],
    fail: 'Se a comparação nunca é aberta, mover para o Histórico (E7) e deixar o Hoje só com o plano atual.' },

  { id: 'E4', name: 'Tarefas dentro do dia', short: 'Tarefas', wave: 'w2', pri: 'P0', deps: ['E2'], dur: '1–2 semanas', icon: 'tasks', state: 'aprovada',
    nav: ['hoje', 'tarefas', 'config'], hero: 's4Today', wf: ['s4Today', 'palette', 'tasks'],
    q: 'Ligar tarefas aos blocos melhora o que eu faço em cada bloco?',
    why: 'Tarefas alimentam o Hoje, não o substituem. Esta etapa testa a ligação tarefa ↔ bloco com o mínimo de campos.',
    feats: [
      ['command', 'Captura rápida por ⌘K, tecla N e + no celular, direto para o Inbox', ['CAP-C7', 'US-TASK-001']],
      ['tasks', 'Tarefas: Inbox, Backlog, Em andamento, Concluídas', ['CAP-E1']],
      ['pencil', 'Campos mínimos: título, área, prioridade, estimativa, prazo', ['CAP-E3', 'US-TASK-002']],
      ['listChecks', 'Triagem do Inbox com teclado', ['CAP-E2', 'US-TASK-007']],
      ['move', 'Arrastar tarefa para um bloco; carga × capacidade do bloco (só aviso)', ['CAP-B8', 'CAP-B10', 'US-PLAN-006', 'US-PLAN-007']],
      ['check', 'Concluir tarefa; ao fechar o dia, não concluídas voltam ao Backlog', ['CAP-C5', 'US-TASK-005']],
      ['history', 'Continuar de dias anteriores no Hoje', ['US-TASK-006', 'US-PLAN-005']],
      ['layers', 'Área da tarefa × área do bloco: ao arrastar, blocos da mesma área se destacam; em área diferente, aviso leve com “Mover para Maker” ou “Manter”', ['DIA-04']],
    ],
    not: ['Subtarefas, projetos, tags, recorrência (E12)', 'Timer de foco (E6)'],
    grow: ['Captura rápida (⌘K)', 'Inbox e Backlog', 'Triagem com teclado', 'Tarefa → bloco + capacidade', 'Área da tarefa × bloco', 'Continuar de dias anteriores'],
    daily: [
      ['Quantas tarefas você anotou fora do app hoje?', '0 · 1–2 · 3+'],
      ['As tarefas dos blocos foram as que você fez?', '1 a 5'],
    ],
    retro: [
      ['Você preencheu estimativas por hábito ou por obrigação?', 'Hábito · Obrigação · Não preenchi'],
      ['Algum campo sobrou?', 'Prioridade · Estimativa · Prazo · Área · Nenhum'],
      ['O aviso de capacidade mudou alguma decisão?', 'Sim · Não'],
    ],
    logs: [
      ['task_quick_captured', 'surface, chars, ms_to_submit', 'A captura é rápida?'],
      ['task_triaged', 'fields_set, ms', 'Quais campos são preenchidos'],
      ['task_scheduled / task_unscheduled', 'target (block | slot | backlog)', 'Tarefas são planejadas nos blocos?'],
      ['task_completed', 'had_estimate, in_block, days_open', 'O que é concluído'],
      ['block_capacity_exceeded', 'over_min, action', 'O aviso importa?'],
    ],
    crit: ['Captura com p50 abaixo de 5 s', '60% ou mais das tarefas concluídas estavam num bloco', 'Campos com menos de 10% de uso vão para a lista de corte'],
    fail: 'Se tarefas raramente entram em blocos, testar a variação “tarefas do dia” sem blocos antes de seguir para a E5.' },

  { id: 'E5', name: 'Planejamento guiado', short: 'Planejamento', wave: 'w2', pri: 'P1', deps: ['E3', 'E4'], dur: '2 semanas', icon: 'listChecks', state: 'aprovada',
    nav: ['hoje', 'tarefas', 'config'], hero: 'allocate', wf: ['unplanned', 'ctx', 'skeleton', 'allocate', 'conflicts', 'quick', 'lateStart'],
    q: 'Um ritual de manhã em etapas deixa o dia melhor do que só aceitar o template?',
    why: 'Com tarefas (E4) e revisões (E3) prontas, dá para testar o planejamento completo contra o modo rápido de forma justa.',
    feats: [
      ['sunrise', 'Hoje Não planejado com o dia preparado (template, pendências, prazos, Inbox)', ['CAP-B1', 'US-PLAN-013']],
      ['listChecks', 'As 4 etapas puláveis: Contexto (com ações), Montar o dia (blocos + tarefas juntos), Conflitos, Iniciar', ['CAP-B2', 'CAP-B3', 'CAP-B11', 'DIA-03']],
      ['command', 'Capturar tarefa ou compromisso sem sair do planejamento (N, ⌘K, clique em horário vazio)', ['DIA-04', 'F-11']],
      ['zap', 'Modo rápido formal (tela única)', ['US-PLAN-010', 'F-02']],
      ['clock', 'Início tardio: iniciar a partir de agora', ['CAP-B13', 'US-PLAN-011', 'Q-07']],
      ['refresh', 'Replanejar restante do dia (proposta determinística)', ['CAP-D3', 'US-REPLAN-004', 'Q-19']],
      ['moon', 'Experimento: planejar amanhã na noite anterior', ['CAP-B14', 'US-PLAN-012', 'Q-08']],
    ],
    not: ['Compromissos de calendário no Contexto (E9)'],
    grow: ['Dia preparado', 'Planejamento em 4 etapas', 'Modo rápido', 'Início tardio', 'Replanejar restante'],
    daily: [
      ['Qual modo você usou hoje?', 'Completo · Rápido · Nenhum'],
      ['O dia planejado foi realista?', '1 a 5'],
    ],
    retro: [
      ['Qual etapa você pularia sempre?', 'Contexto · Montar o dia · Conflitos · Nenhuma'],
      ['O modo completo compensa o tempo?', '1 a 5'],
      ['Planejar na noite anterior funcionou?', 'Sim · Não · Não testei'],
    ],
    logs: [
      ['day_planning_started', 'mode, hour', 'Qual modo prevalece'],
      ['planning_stage_viewed / planning_stage_skipped', 'stage, ms', 'Etapas que ninguém usa'],
      ['planning_abandoned', 'stage', 'Onde o ritual quebra'],
      ['day_started', 'mode, planning_ms', 'Custo do planejamento'],
      ['replan_remaining_used', 'accepted, edited_after', 'A proposta automática serve?'],
    ],
    crit: ['Completo com p50 abaixo de 5 min; rápido abaixo de 1 min', 'Etapa pulada em mais de 70% das vezes: cortar ou fundir', 'Realismo 3,5 ou mais nos dois modos: modo rápido vira o padrão'],
    fail: 'Se o completo não bate o rápido em realismo, o completo vira opcional e escondido.' },

  { id: 'E6', name: 'Foco', short: 'Foco', wave: 'w2', pri: 'P1', deps: ['E4'], dur: '1–2 semanas', icon: 'clock', state: 'aprovada',
    nav: ['hoje', 'tarefas', 'config'], hero: 'active', wf: ['active', 'focusEnd', 'forgot'],
    q: 'Sessões de foco valem o atrito, ou o Comecei/Terminei já basta?',
    why: 'A spec generaliza Pomodoro como Focus Session. A pergunta é se o timer muda o trabalho ou só gera mais dado.',
    feats: [
      ['clock', 'Presets 25/5, 30/5, 45/10, 50/10, 60/10, livre e cronômetro', ['US-TIME-001', 'US-TIME-003']],
      ['play', 'Timer no card Agora e no título da aba', ['CAP-C3', 'CAP-C4']],
      ['tasks', 'Sessões acumulam na tarefa; estimado × rastreado', ['US-TIME-002', 'US-TIME-006']],
      ['coffee', 'Pausas, sessões interrompidas, +5 min', ['F-15']],
      ['alert', 'Timer esquecido: “Parou quando?”', ['CAP-F6', 'US-TIME-007']],
      ['pencil', 'Editar e excluir sessões', ['CAP-F5']],
      ['refresh', 'Timer visível em todos os dispositivos', ['US-OFFLINE-006', 'Q-30']],
    ],
    not: ['Estatísticas de foco (E11)'],
    grow: ['Timer de foco', 'Sessões por tarefa', 'Timer esquecido', 'Timer multi-dispositivo'],
    daily: [
      ['Usou foco hoje? Se não, por quê?', 'Usei · Esqueci · Não precisava · Atrapalha'],
      ['O timer interrompeu algo importante?', 'Sim · Não'],
    ],
    retro: [
      ['O foco mudou como você trabalha?', '1 a 5'],
      ['Qual preset você mais usou?', 'Lista dos presets'],
    ],
    logs: [
      ['focus_session_started', 'preset, task?, block?', 'Quando o foco é usado'],
      ['focus_session_finished', 'planned_min, actual_min, interrupted', 'Sessões completas × interrompidas'],
      ['focus_break_started / skipped', 'preset', 'As pausas são respeitadas?'],
      ['timer_forgotten_fixed', 'running_min, corrected_min', 'Frequência do timer esquecido'],
      ['session_edited / session_deleted', 'reason', 'Erros de uso'],
    ],
    crit: ['Foco usado em 50% ou mais dos dias de trabalho', 'Timer esquecido menos de 1 vez por semana depois dos ajustes', 'Nota “mudou como trabalho” 3 ou mais'],
    fail: 'Se não passar, o foco vira opcional e escondido; o Comecei/Terminei continua sendo o padrão.' },

  { id: 'E7', name: 'Fechar o ciclo e Histórico', short: 'Histórico', wave: 'w3', pri: 'P1', deps: ['E2', 'E4'], dur: '2 semanas', icon: 'history', state: 'aprovada',
    nav: ['hoje', 'tarefas', 'historico', 'config'], hero: 'history', wf: ['closeRepair', 'closeTasks', 'summary', 'history', 'nextday', 'midnight'],
    q: 'Fechar o dia e olhar para trás muda o planejamento seguinte?',
    why: 'Fecha o ciclo Planejar → Executar → Revisar → Aprender. Depende de ter real (E2) e tarefas (E4) para ter o que revisar.',
    feats: [
      ['moon', 'Fechamento completo em 4 passos: real, tarefas, reflexão opcional, resumo', ['CAP-G1', 'CAP-G2', 'CAP-G3', 'CAP-G4']],
      ['refresh', 'Reabrir o dia', ['CAP-G5', 'US-REVIEW-005', 'F-22']],
      ['history', 'Histórico em calendário e lista, com a “forma” de cada dia', ['CAP-H1']],
      ['panels', 'Detalhe do dia: Baseline, Final, Real, Tarefas, Stats, Revisões', ['CAP-H2']],
      ['pencil', 'Edição histórica de qualquer dia', ['CAP-H3', 'US-TIME-005', 'F-08']],
      ['moon', 'Dias que cruzam a meia-noite', ['F-23']],
    ],
    not: ['Estatísticas agregadas (E11)'],
    grow: ['Fechamento em 4 passos', 'Reabrir dia', 'Histórico', 'Edição histórica'],
    daily: [
      ['A reflexão foi útil ou só mais um campo?', 'Útil · Indiferente · Atrapalha · Pulei'],
      ['Você editou algum dia passado hoje?', 'Sim (por quê?) · Não'],
    ],
    retro: [
      ['O histórico mudou alguma decisão sua?', 'Sim (qual?) · Não'],
      ['Com que frequência você abriria o histórico?', 'Diária · Semanal · Raramente'],
    ],
    logs: [
      ['day_closed', 'steps_completed, reflection_filled, energy', 'Quais passos importam'],
      ['day_reopened', 'hours_after_close', 'Fechar cedo demais?'],
      ['history_opened', 'view, days_back', 'O passado é consultado?'],
      ['historical_edit_performed', 'days_ago, kind', 'Frequência de correção'],
      ['day_auto_closed', 'open_days', 'Dias esquecidos'],
    ],
    crit: ['Edições históricas nunca alteram o Baseline (verificado nos logs)', 'Reflexão preenchida em menos de 30% dos dias: vira opcional e escondida', 'Histórico aberto pelo menos 1 vez por semana'],
    fail: 'Se o histórico não é aberto, ele fica só como fonte de dados para Insights e sai da navegação principal.' },

  { id: 'E8', name: 'Celular de verdade e offline', short: 'Celular', wave: 'w3', pri: 'P1', deps: ['E2', 'E4', 'E6'], dur: '1 semana', icon: 'phone', state: 'aprovada',
    nav: ['hoje', 'tarefas', 'historico', 'config'], hero: 'mobile', wf: ['mobile', 'offline'],
    q: 'Consigo viver o dia pelo celular quando estou longe do computador?',
    why: 'Grande parte do registro ao vivo acontece longe do desktop. Depois de E2, E4 e E6, o celular tem o que precisa para ser completo.',
    feats: [
      ['phone', 'Layout mobile completo: Hoje, Tarefas, Histórico, Mais; bottom sheets', ['SCR-MOBILE']],
      ['play', 'Comecei/Terminei, captura, timer e fechar dia pelo celular', ['US-OFFLINE-003']],
      ['cloudOff', 'Offline robusto: fila visível, reconciliação e conflitos leves', ['CAP-A3', 'US-OFFLINE-001', 'US-OFFLINE-002', 'US-OFFLINE-004', 'US-OFFLINE-005']],
      ['info', 'Notificações opcionais: fim do timer e troca de bloco', ['CAP-K5', 'US-EXEC-004', 'Q-18']],
    ],
    not: ['App nativo e widgets (Horizonte)'],
    grow: ['Mobile completo', 'Offline robusto', 'Notificações'],
    daily: [
      ['Usou o celular para registrar algo hoje?', 'Sim · Não'],
      ['Perdeu algum dado ou viu algo duplicado?', 'Sim · Não'],
    ],
    retro: [
      ['As notificações ajudam ou incomodam?', 'Ajudam · Indiferente · Incomodam'],
      ['O que ainda te obriga a ir para o desktop?', 'Texto livre'],
    ],
    logs: [
      ['app_opened', 'device, standalone', 'Uso por dispositivo'],
      ['offline_started / offline_ended', 'duration_s, ops_queued', 'Quanto uso offline'],
      ['sync_queue_flushed', 'ops, ms', 'Latência da reconciliação'],
      ['sync_conflict', 'entity, resolution', 'Conflitos reais'],
      ['notification_shown / notification_clicked', 'kind', 'Notificações úteis?'],
    ],
    crit: ['Nenhuma perda de dado', '30% ou mais dos registros ao vivo feitos no celular', 'Menos de 1 conflito por semana'],
    fail: 'Perda de dado bloqueia tudo: corrigir antes de qualquer etapa seguinte.' },

  { id: 'E9', name: 'Calendários (leitura)', short: 'Calendários', wave: 'w4', pri: 'P2', deps: ['E3', 'E5'], dur: '2 semanas', icon: 'calendar', state: 'aprovada',
    nav: ['hoje', 'tarefas', 'historico', 'config'], hero: 'ctx', wf: ['calendars', 'ctx', 'conflict', 'cancelled'],
    q: 'Trazer a agenda para dentro do Hoje reduz surpresas?',
    why: 'Depende das revisões (E3) para tratar conflitos e do planejamento (E5) para mostrar compromissos no Contexto.',
    feats: [
      ['cloud', 'Google (vários calendários) e Microsoft 365 do trabalho', ['CAP-J1', 'US-CAL-001']],
      ['eye', 'Classificação Commitment / Awareness / Oculto por calendário, com exceção por evento', ['CAP-J2', 'CAP-J3', 'US-CAL-002', 'US-CAL-008']],
      ['calendar', 'Compromissos na timeline e no Contexto do planejamento', ['US-CAL-003', 'US-PLAN-003', 'US-PLAN-004']],
      ['alert', 'Reunião nova gera conflito; cancelamento ou mudança gera revisão', ['CAP-D2', 'US-CAL-006', 'US-CAL-007']],
      ['refresh', 'Status e erros de sincronização', ['CAP-J6', 'US-CAL-009']],
    ],
    not: ['Escrever no calendário externo (E10)'],
    grow: ['Google e Microsoft', 'Commitment / Awareness', 'Conflitos com reuniões'],
    daily: [
      ['Alguma reunião te pegou de surpresa hoje?', 'Sim · Não'],
      ['Algum evento estava classificado errado?', 'Sim · Não'],
    ],
    retro: [
      ['Você consultou os eventos Awareness?', 'Sempre · Às vezes · Nunca'],
      ['Vale ver os calendários no planejamento?', '1 a 5'],
    ],
    logs: [
      ['calendar_synced', 'provider, events, ms, error?', 'Confiabilidade do sync'],
      ['calendar_event_classified', 'from, to, scope', 'Padrões por calendário estão certos?'],
      ['external_conflict_detected / resolved', 'action', 'Como reuniões mudam o dia'],
      ['external_event_changed_applied', 'kind', 'Mudanças externas absorvidas'],
    ],
    crit: ['No máximo 1 surpresa por semana', 'Reclassificações manuais caindo semana a semana', 'Nenhum sync falhando em silêncio'],
    fail: 'Se Awareness nunca é consultado, fundir com Oculto e simplificar a classificação.' },

  { id: 'E10', name: 'Proteger o tempo', short: 'Proteger', wave: 'w4', pri: 'P2', deps: ['E9'], dur: '2 semanas', icon: 'shield', state: 'aprovada',
    nav: ['hoje', 'tarefas', 'historico', 'config'], hero: 'publish', wf: ['publish'],
    q: 'Publicar blocos como Busy protege o foco de verdade?',
    why: 'Escrever em calendário externo é a integração mais arriscada; só vem depois que a leitura (E9) está estável.',
    feats: [
      ['shield', 'Publicar bloco: Interno, Google, Microsoft ou Ambos; Busy ou Free', ['CAP-J4', 'US-CAL-004', 'US-CAL-005']],
      ['move', 'Mover o bloco move o evento externo', ['F-07']],
      ['x', 'Excluir: só no DailyFlow ou também no calendário', ['CAP-J5']],
      ['alert', 'Falhas de publicação visíveis, com Tentar de novo', ['F-07']],
    ],
    not: [],
    grow: ['Publicar como Busy'],
    daily: [['Alguém marcou reunião em cima de um bloco protegido?', 'Sim · Não']],
    retro: [['O tempo protegido virou tempo focado?', '1 a 5']],
    logs: [
      ['block_published', 'target, availability', 'O que é protegido'],
      ['published_block_moved / deleted', 'scope', 'Sincronia do evento externo'],
      ['publish_failed', 'provider, error', 'Confiabilidade'],
    ],
    crit: ['Nenhum evento órfão no calendário externo', 'Menos de 1 invasão de reunião por semana em blocos protegidos'],
    fail: 'Se publicar não reduz invasões, manter só a leitura (E9).' },

  { id: 'E11', name: 'Insights', short: 'Insights', wave: 'w5', pri: 'P2', deps: ['E6', 'E7'], dur: '3–4 semanas', icon: 'chart', state: 'aprovada',
    nav: ['hoje', 'tarefas', 'historico', 'insights', 'config'], hero: 'insights', wf: ['insights', 'summary'],
    q: 'Quais estatísticas mudam meu comportamento e quais são só curiosidade?',
    why: 'Só vem depois de semanas de dados reais. A spec pede guardar dados ricos primeiro e construir estatísticas aos poucos.',
    feats: [
      ['chart', 'Distribuição por Life Area na semana e no mês', ['CAP-I1', 'US-STATS-001', 'US-STATS-004']],
      ['layers', 'Planejado × real', ['CAP-I2', 'US-STATS-002']],
      ['pencil', 'Precisão das estimativas por categoria', ['CAP-I3', 'US-STATS-003']],
      ['clock', 'Estatísticas de foco', ['CAP-I4']],
      ['calendar', 'Formato do dia (day shape)', ['CAP-I5', 'US-STATS-005']],
      ['refresh', 'Comparar períodos e metas semanais por área', ['CAP-I6', 'US-STATS-007', 'US-STATS-008']],
    ],
    not: ['Pontuação de produtividade (fora do produto por princípio)'],
    grow: ['Distribuição por área', 'Planejado × real', 'Precisão de estimativas', 'Formato do dia'],
    daily: [],
    retro: [
      ['Algum gráfico fez você mudar algo nesta semana?', 'Sim (qual?) · Não'],
      ['Qual gráfico você nunca olhou?', 'Lista dos gráficos'],
    ],
    logs: [
      ['insights_viewed', 'section, period, dwell_s', 'O que é visto'],
      ['insight_interacted', 'chart, action', 'O que é explorado'],
      ['weekly_goal_set', 'area, minutes', 'Metas fazem sentido?'],
    ],
    crit: ['Gráfico sem visita em 3 semanas: remover', 'Pelo menos 1 mudança de comportamento relatada por mês'],
    fail: 'Manter só os gráficos que passaram; o resto sai.' },

  { id: 'E12', name: 'Refinamento e dados', short: 'Refinamento', wave: 'w5', pri: 'P2', deps: ['E4', 'E7'], dur: 'contínuo', icon: 'gear', state: 'aprovada',
    nav: ['hoje', 'tarefas', 'historico', 'insights', 'config'], hero: 'template', wf: ['template', 'tasks'],
    q: 'O que ainda falta para o DailyFlow ser o único lugar do meu dia?',
    why: 'Só entra o que as etapas anteriores provaram que faz falta. Os campos avançados ficam por último para não pesar o núcleo.',
    feats: [
      ['tasks', 'Subtarefas, projetos, tags, notas e recorrência', ['CAP-E4', 'CAP-E5', 'US-TASK-008', 'Q-09']],
      ['filter', 'Busca e filtros avançados de tarefas', ['CAP-E6', 'US-TASK-009']],
      ['calendar', 'Agendar tarefa para um dia futuro; salvar o dia como template', ['Q-17', 'Q-23']],
      ['gear', 'Categorias, presets, exibição e notificações', ['CAP-K3', 'CAP-K4', 'CAP-K6']],
      ['download', 'Exportação completa dos dados (JSON / CSV)', ['CAP-K7', 'US-SET-004']],
      ['tasks', 'Tarefas em quadro (Inbox → Backlog → Today → Done) no lugar das abas: arrastar entre colunas no desktop; no celular, colunas deslizáveis e segurar o card abre um dock com as colunas. Ao cair no Today sem estar planejada: “Onde ela cabe?” (blocos que restam, mesma área primeiro, tempo livre, bloco novo no próximo vão, começar agora ou deixar sem bloco) e marca “+hh:mm” se o dia já tinha começado', ['CAP-E1', 'US-PLAN-006', 'DIA-04']],
    ],
    not: [],
    grow: ['Campos avançados de tarefa', 'Recorrência', 'Exportação completa'],
    daily: [],
    retro: [['Ainda usa outro app de tarefas ou agenda? Para quê?', 'Texto livre']],
    logs: [
      ['field_filled', 'field, entity', 'Campos que sobrevivem'],
      ['recurrence_created', 'rule', 'Recorrência é usada?'],
      ['export_done', 'format, rows', 'Exportação'],
      ['task_moved / task_fit_chosen', 'from, to, surface · choice (block | new_block | focus | keep | dismiss), same_area, over_min', 'O quadro e o “onde cabe” são usados?'],
    ],
    crit: ['Nenhuma dependência de outro app para o fluxo diário'],
    fail: 'Cortar o que não for usado em 4 semanas.' },

  { id: 'EH', name: 'Horizonte: Android, widgets, relógio, floresta', short: 'Horizonte', wave: 'wh', pri: 'P3', deps: ['E8', 'E11'], dur: 'depois da validação', icon: 'watch', state: 'aprovada',
    nav: ['hoje', 'tarefas', 'historico', 'insights', 'config'], hero: 'widget', wf: ['widget'],
    q: 'Depois de validado na web, onde o DailyFlow precisa estar para eu nem precisar abrir o app?',
    why: 'A spec pede validar tudo na web/PWA antes de reproduzir no Android. Esta etapa só é planejada com os dados das anteriores.',
    feats: [
      ['phone', 'App Android (decidido: Expo como casca do webapp, ver última entrega)', []],
      ['panels', 'Widgets: bloco atual, timeline, tarefas, próximas tarefas, progresso', ['CAP-L1', 'US-WIDGET-001', 'US-WIDGET-002', 'US-WIDGET-003']],
      ['lock', 'Tela de bloqueio e Always-On Display', ['CAP-L2', 'US-WIDGET-004']],
      ['watch', 'Wear OS: complicação, tile, app', ['CAP-L3']],
      ['sunrise', 'Gamificação estilo floresta', ['CAP-L4']],
      ['panels', 'Widget Dia (4x4): agora (foco, em andamento, não iniciado com ▶, livre, dia encerrado), faixa do dia, próximo e to-dos de hoje que dá para marcar no próprio widget', ['CAP-L1', 'US-WIDGET-001', 'US-WIDGET-003']],
      ['refresh', 'Atualizações OTA (EAS Update, canal production): mudanças de JS chegam no app sem reinstalar', []],
      ['phone', 'App = o próprio webapp numa casca nativa (WebView logada com o token do aparelho): web e app têm sempre as mesmas funcionalidades; o nativo só faz widgets, notificação, OTA e links', []],
    ],
    not: [],
    grow: ['Android e widgets', 'Relógio', 'Floresta'],
    daily: [], retro: [], logs: [['widget_opened_app', 'widget', 'Widgets substituem abrir o app?']],
    crit: ['Definidos quando a etapa for planejada'], fail: '' },

  { id: 'EF', name: 'Floresta viva', short: 'Floresta', wave: 'wh', pri: 'P3', deps: ['EH', 'E7', 'E11'], dur: '2–3 semanas', icon: 'sunrise', state: 'rascunho',
    nav: ['hoje', 'insights'], hero: '', wf: [],
    q: 'Ver a vida crescer num mundo bonito me faz querer viver o plano, sem virar placar nem culpa?',
    why: 'Nota #24: a Floresta atual (grade de 12 semanas com árvores SVG paradas) é feia, desmotivante e inútil. A refação troca a grade por um mundo vivo, com cara de jogo e muita animação, mantendo a regra da spec (§85): representa como a vida foi vivida, nada é perdido, descanso e família crescem igual, sem pontuação de produtividade.',
    feats: [
      ['sunrise', 'Arte primeiro: árvores low-poly 3D procedurais e bonitas (tronco com galhos, copa em camadas, luz suave, sombra, vento balançando), uma espécie por área com variações de idade (broto → muda → árvore → ancestral); protótipo visual aprovado antes de qualquer outra coisa', ['CAP-L4']],
      ['layers', 'Um mundo só no lugar da grade: ilha 3D em que cada área é uma região (bioma próprio: Maker com vagalumes, Música com cerejeiras e notas no ar, Família com pomar e casinha, Atividade física com trilha na montanha, Descanso com lago…); arrastar, girar, zoom; tocar numa árvore mostra o dia e o que foi feito', ['CAP-L4']],
      ['clock', 'Crescer ao vivo: enquanto uma atividade roda, uma semente brota e cresce em tempo real (no Forest, no card Agora e na pílula do computador); ao terminar, a árvore “assenta” na ilha com partículas', []],
      ['moon', 'Ciclo de dia e noite e estações do hemisfério sul de verdade: céu, luz e cores mudam com a hora; vagalumes à noite, pássaros de dia, folhas no outono', []],
      ['check', 'Recap ao fechar o dia: câmera passa pelas árvores novas, contadores sobem, desbloqueios aparecem (o momento de recompensa)', ['US-CLOSE-001']],
      ['chart', 'Progressão por área, sem placar global: cada região sobe de nível com o tempo vivido e ganha decorações (trilha, banco, ponte, cabana, cachoeira…); nada diminui', []],
      ['tasks', 'Coleção (herbário) com raridades: espécies comuns por área e raras por padrões saudáveis (ex.: 5 dias com Música na semana, um dia com todas as áreas, descanso de verdade num domingo); conquistas sem sequência que quebra (ritmo medido em 28 dias)', []],
      ['flag', 'Missões semanais opcionais a partir das metas por área (E11): “3h de Música esta semana” → decoração especial', ['E11']],
      ['history', 'Time-lapse: deslizar no tempo e ver a ilha crescer semana a semana', []],
      ['gear', 'Movimento reduzido e aparelho fraco: versão 2D ilustrada com as mesmas regras; som opcional, desligado por padrão', []],
    ],
    not: ['Pontuação de produtividade ou ranking', 'Árvore que morre, murcha ou sequência que se perde', 'Recompensa por trabalhar mais que o planejado', 'Assets de terceiros: tudo procedural ou desenhado para o app'],
    grow: ['Árvores bonitas', 'Ilha viva', 'Crescer ao vivo', 'Recap do dia', 'Níveis e coleção', 'Missões e time-lapse'],
    daily: [],
    retro: [['A Floresta te dá vontade de viver o plano? (1–5)', 'Escala'], ['Abriu a Floresta sem precisar? O que procurou lá?', 'Texto livre'], ['Algo na Floresta pareceu cobrança ou culpa?', 'Texto livre']],
    logs: [
      ['forest_opened', 'source (nav | recap | now_card | mini), ms_visible', 'A ilha é visitada espontaneamente?'],
      ['forest_tree_tapped / forest_region_tapped', 'area, age_days', 'Explora o próprio histórico?'],
      ['forest_recap', 'shown, skipped_at_ms, new_trees, unlocks', 'O recap é visto até o fim?'],
      ['forest_unlock', 'kind (species | decoration | achievement), id, rarity', 'Desbloqueios acontecem num ritmo bom?'],
      ['forest_quest', 'id, state (offered | done | ignored)', 'Missões ajudam ou atrapalham?'],
    ],
    crit: ['Abre a Floresta por conta própria pelo menos 2× por semana', 'Recap visto até o fim em mais da metade dos dias fechados', 'Nenhuma resposta de culpa ou cobrança na retro'],
    fail: 'Se não motivar em 3 semanas, voltar para uma vista contemplativa simples (sem progressão) e cortar missões e níveis.' },
];

const STAGE_KIT = {
  principles: [
    ['calendar', 'Cada etapa é usável de verdade', 'Nada de protótipo descartável: termina com o app em uso diário, mesmo que pequeno.'],
    ['help', 'Uma pergunta por etapa', 'Cada etapa existe para responder uma pergunta sobre o framework, não para entregar uma lista de telas.'],
    ['layers', 'Logs desde o primeiro dia', 'Toda interação vira evento. As perguntas objetivas complementam o que o log não enxerga.'],
    ['flag', 'Toda etapa termina numa decisão', 'Avançar, ajustar e repetir, ou cortar a funcionalidade. Cortar também é resultado.'],
  ],
  questions: [
    { id: 'EQ-1', q: 'Qual a duração mínima de validação de cada etapa?', rec: 'A indicada em cada etapa (1–2 semanas na maioria), incluindo pelo menos um fim de semana.' },
    { id: 'EQ-2', q: 'Durante a validação você usa só o DailyFlow ou mantém seu sistema atual em paralelo?', rec: 'Em paralelo até a E4; a partir da E4, só o DailyFlow para o que ele já cobre. Isso deixa as respostas mais honestas.' },
    { id: 'EQ-3', q: 'Quando aparece o check-in diário?', rec: 'No fechamento do dia. Se o dia não for fechado, na primeira abertura do dia seguinte, sobre ontem.' },
    { id: 'EQ-4', q: 'O celular entra desde a E1 (Agora/Próximo) ou só na E8?', rec: 'Desde a E1, só leitura, e Comecei/Terminei na E2. A E8 completa o resto.' },
    { id: 'EQ-5', q: 'Os calendários deveriam vir antes?', rec: 'Se reuniões dominam seus dias de trabalho, a leitura (E9) pode vir logo depois da E3. Hoje está depois do planejamento guiado.' },
    { id: 'EQ-6', q: 'Os critérios de passagem bloqueiam o avanço ou só orientam?', rec: 'Orientam. A decisão é sua na retro, olhando números e respostas juntos.' },
    { id: 'EQ-7', q: 'Por quanto tempo guardar os logs de produto?', rec: 'Para sempre durante a validação (volume pequeno, single-user). Revisar depois do Horizonte.' },
    { id: 'EQ-9', q: 'Onde fica o que depende de credenciais ou de aparelho?', rec: 'Decidido em 05/10: em branches sem merge, para testar com você. feat/e9-calendars (OAuth Google/Microsoft + migração), feat/e10-protect (empilhada na E9) e feat/eh-horizon (floresta no web, pareamento + snapshot, app Android com widgets, Wear OS). E11 e E12 foram direto para produção porque dava para testar tudo aqui.' },
    { id: 'EQ-8', q: 'Desenvolver etapa por etapa ou E2–E8 de uma vez?', rec: 'Decidido em 05/10: de uma vez. Etapa por etapa deixava o app pequeno demais para valer o uso diário. E2–E8 foram construídas numa noite e validadas juntas: um check-in combinado (4 perguntas) e eventos marcados com a etapa “E2-E8”. Os critérios de cada etapa continuam valendo na retro.' },
  ],
  schema: [
    ['id', 'uuid', 'Identificador do evento'],
    ['ts', 'timestamp com fuso', 'Quando aconteceu (local e UTC)'],
    ['stage', 'E1…E12', 'Etapa ativa quando o evento aconteceu'],
    ['session_id', 'uuid', 'Agrupa uma sessão de uso'],
    ['device', 'desktop | mobile | tablet', 'Onde aconteceu'],
    ['screen', 'texto', 'Tela ou superfície (hoje, tarefas, ⌘K…)'],
    ['event', 'texto', 'Nome do evento (snake_case)'],
    ['props', 'JSON', 'Propriedades do evento'],
    ['day', 'data', 'Dia lógico (respeita a virada das 04:00)'],
  ],
  always: [
    ['Dias com o app aberto', 'today_opened por dia'],
    ['Aberturas por dia e por dispositivo', 'app_opened'],
    ['Tempo até a primeira ação útil', 'app_opened → primeira mutação'],
    ['Cliques ou passos por tarefa-chave', 'sequência de eventos por fluxo'],
    ['Check-ins respondidos × pulados', 'validation_answered.skipped'],
    ['Erros e falhas de sync', 'error_logged, sync_completed.error'],
  ],
};
